### ISSUE TITLE
[DevEx]: Rename `api/helpers/gamestate` folder to `api/helpers/gameStates`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#1002]
### Improvement Summary

To be more consistent, we should change the name of the `api/helpers/gamestate` folder to `api/helpers/gameStates`

### Detailed Description

This will also require updating every caller of those helpers so that any reference to `sails.helpers.gamestate` is replaced with `sails.helpers.gameStates`.

**Comment by Mang0codes** [comment]
I think this issue has been solved by #1070

**Comment by itsalaidbacklife** [comment]
> I think this issue has been solved through #1070  @itsalaidbacklife is that correct?

Correct, I believe the PR was missing 
> Resolves #1002

From the description so it didn't close automatically

**Comment by Mang0codes** [comment]
> > I think this issue has been solved through #1070  @itsalaidbacklife is that correct?
> 
> Correct, I believe the PR was missing
> 
> > Resolves #1002
> 
> From the description so it didn't close automatically

There was another issue with this same description #1028 , the one I raised a PR for, that's why I thought about letting you know so it doesn't create any confusion later. 😄

**Comment by itsalaidbacklife** [comment]
Ha. Yep total duplicate. Good catch -- thank you!
