### ISSUE TITLE
[Feature]: Add text with rules for 3 and 4 player Cuttle

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#1009]
### Feature Summary

The rules for 3 and 4 player Cuttle were accidentally removed in the redesign and implementation #888. We should add them back after the one-offs section and before faq.

### Detailed Description

The text already exists in the translation files, it's simply not displayed. We should add it to `src/routes/rules/RulesView.vue` in its own `<section>` with the same `v-intersect` config as the other sections and its own `id="multiplayer"`. A corresponding entry should be made to `src/routes/rules/rulesData`'s `sectionTitles` to ensure the section appears in the `RulesNav`. The text should be rendered using `i18n` by passing the translation keys to the already-imported `t()` function. See the FAQ section of the `RulesView` for examples.

The heading should be the text at the key `rules.multiplayerText2` followed by a `<p>` that combines the text from the `rules.multiplayerText1` and `rules.multiplayerText2` strings which include a link to cuttle.cards in the middle. It should read:

> Presently only 2-player cuttle is available at [cuttle.cards](https://cuttle.cards), however Cuttle can be played with 2-4 players. 3 and 4-player Cuttle each have slight variations on the rules to optimize the game balance while changing the pace and the feel. Give them a try next time you're playing Cuttle in a group!

There should then be sub-headings and divs for the `rules.3Players` and `rules.4Players` blocks found in the translation files e.g. `en.json`.  These should have the heading, a paragraph of text, and then a bulleted list of all their individual rules. It is likely a good idea to create a component to represent these sub-sections since they will be almost identical in the 3Player and 4Player sub-sections.

**Comment by livoszlak** [comment]
Hi! I'm new to open source, currently studying web dev. I saw in the contributor's guide that you don't generally assign issues, but I just wanted to say hi as a first time contributor - this looks like a fun project! Trying my hand at this issue to start. 😸 👋

**Comment by Haviles04** [comment]
> Hi! I'm new to open source, currently studying web dev. I saw in the contributor's guide that you don't generally assign issues, but I just wanted to say hi as a first time contributor - this looks like a fun project! Trying my hand at this issue to start. 😸 👋  

Awesome! Glad to have you! If you have any questions, feel free to ask. We also have a pretty active discord that has a section just for code.[Discord](https://discord.com/invite/saVUZ6uX) :)
