### ISSUE TITLE
[Feature]: Automatically join a game after creating it

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#1036]
### Feature Summary

When a player creates a new game from the Home page, we should immediately subscribe them to it and add them to the game

### Detailed Description

Creating a game is done via in the frontend via the `src/routes/home/components/CreateGameDialog.vue` using the backend’s `api/controllers/game/create` action. Currently, the game is created but the requesting user is not put into the game or subscribed to its updates. We should revise this flow so the requesting user is automatically put into the game and brought to its lobby page. 

We can accomplish this on the frontend by making the CreateGameDialog navigate to the lobby of the new game by capturing the game id from the response to the create game request and calling 
```
this.$router.push(`/lobby/${gameId}`)
```

**Comment by Haviles04** [comment]
Closed by #1079
