### ISSUE TITLE
[DevEx]:  Fix max-width prop value in `VSkeletonLoader` instances in the `HomeView` by using number instead of string

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#1037]
### Improvement Summary

See #1018 as a similar example. The `max-width` prop should have a numeric value rather than a string value. We should do this by adding a `:` in front of the `max-width` prop for the `v-skeleton-loader` instances in the `HomeView`

### Detailed Description

This should fix the console warnings due to this misconfigured prop.

**Comment by angelbaezsa** [comment]
I think I can contribute to this issue, please assign it to me

**Comment by itsalaidbacklife** [comment]
> I think I can contribute to this issue, please assign it to me

@angelbaezsa we can't officially assign issues outside of organization members, but your help would be welcome in addressing the this issue. Have at it!
