### ISSUE TITLE
[Feature]: Show status of match in GameOverDialog

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#105]
### Feature Summary

When a game is finished, if it is a ranked game, we should show players the status of their current match

### Detailed Description

As a player competing in a ranked match, I would like to see my score against my current opponent in our current match for this week after our ranked game ends.

We should redesign the `GameOverDialog` to display this information.

It should show you how many games you've played during this match, in order, with whether each was a win, a loss, or a stalemate, and it should say whether your match is in progress, or won/lost like

1. You won your match against <opponent_username>
2. You lost your match against <opponent_username>
3. Your match against <opponent_username> is in progress

**Comment by itsalaidbacklife** [comment]
Proposed design:
![image](https://user-images.githubusercontent.com/6520704/219157354-36d94052-f0bd-444c-bbc0-7484757e50af.png)


We can tinker with the iconography and coloring, but this gets the idea across. The logo image in the upper right will still show win/loss/stalemate image like we currently do, with different icons for the wins and losses in the list of games below.

**Comment by lihaobhsfer** [comment]
some work in progress

In progress match

<img width="699" alt="image" src="https://user-images.githubusercontent.com/17372464/220634091-91e4814d-25e8-4419-b2bb-a605b3ea12b6.png">


Finished match
<img width="690" alt="image" src="https://user-images.githubusercontent.com/17372464/220633848-c19594fe-ceb3-4555-8047-580f15fc6030.png">

Unranked
<img width="677" alt="image" src="https://user-images.githubusercontent.com/17372464/220634272-0842016e-5b18-4798-ac72-8a3f0cc521b8.png">
