### ISSUE TITLE
[DevEx]: Configure eslint rule to require space in front of comments

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#1050]
### Improvement Summary

To standardize comment formats, we should configure the [spaced-comment](https://eslint.org/docs/latest/rules/spaced-comment) estlint rule to require a whitespace in the beginning of each comment

### Detailed Description

We should then run `npm run lint:fix` to automatically fix all violations across the project.

**Comment by Mang0codes** [comment]
Hi, I'm working on this
