### ISSUE TITLE
Scrap should sort in scuttle order

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#110]
### Bug Summary

The scrap pile should account for suit when sorting so that cards appear in the order of scuttle priority 

### Detailed Description

Currently when sorting the scrap by rank, suit is ignored, resulting in awkward discrepancies from the the expected order.

We should update the CardListSortable to sort by rank then suit (this will also entail updating the associated tests).

**Comment by tygee713** [comment]
I'd like to work on this if it's available.

**Comment by seriouslysean** [comment]
> I'd like to work on this if it's available.

By all means, more than happy to walk you through set up for the app locally if you need it.

The documentation is getting better and should be enough. There's also a a discord if you wanted to stop by the #coding channel. https://discord.gg/qJy7nhWA

I'm @seriouslysean on there, too.
