### ISSUE TITLE
[Feature]: Refactor `.populateGame()` method

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#111]
### Feature Summary

The `.populateGame()` backend method should be cleaned up and refactored

### Detailed Description

`gameService.populateGame()` is the function that creates the data structure sent in the socket events and consumed by the client. It could be improved by

1. Replacing `var` with `const` and `let`
2. Allowing it to be called with any number of players in the game
3. Leveraging `async`/`await`
4. Updating the `tempGame` function to more programatically grab all the attributes off of the `game` it's passed like
```
Object.entries(game).forEach(([key, val]) => {
    if (key === 'players') {
        this[key] = [p0, p1];
        return;
    }
    this[key] = val;
});
```
(note that this can't be done for `tempPlayer` as the player object needs to have at least the `encryptedPassword` field omitted)

**Comment by Haviles04** [comment]
I'd like to give this one a shot
