### ISSUE TITLE
[Feature]: Refactor UI-Facing Strings into json files for internationalization

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#113]
### Feature Summary

In order to support playing Cuttle in different languages, we'll need to pull the strings used in the UI out into reusable json file(s)

### Detailed Description

See [vue docs on localization](https://cli.vuejs.org/dev-guide/ui-localization.html)

**Comment by itsalaidbacklife** [comment]
@seriouslysean I think we'll want to pull this into separate issues per page, and maybe break in-game stuff up further

**Comment by seriouslysean** [comment]
Makes sense to me!

**Comment by itsalaidbacklife** [comment]
I'm closing this as complete, though it's more broadly become the entire internationalization project as we're tackling it page by page
