### ISSUE TITLE
[Bug]: User session is invalid when logging in consecutively

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#116]
### Bug Summary

The `setupGameAsP0()` helper occasionally throws a Type Error due to a 403/forbidden response

### Detailed Description

Cypress appears to be attempting to create a new property on a 403 'error' response when the backend is only sending the string `forbidden`

```
     TypeError: Cannot create property 'stack' on string 'Forbidden'        
                                                                            
Because this error occurred during a `before each` hook we are skipping the 
remaining tests in the current suite: `Countering One-Offs`
```
This happens unpredictably across different tests in the `beforeEach()` hook when using the `setupGameAsP0()` helper function. The issue is likely that one of the commands in that helper function is firing before the appropriate setup has completed, causing the backend to throw a `forbiden()` response

### Steps to Reproduce

1.
2.
3.

**Comment by seriouslysean** [comment]
This actually happens in the app also, not just Cypress which opens up a lot more possibilities for what this might be. I'm not sure how to reproduce it yet, but it seems to happen RIGHT after I log in and view the game list. The error is thrown as it wasn't able to get the list of games (which tracks with where we're seeing the error in Cypress occasionally).

![image](https://user-images.githubusercontent.com/414475/194388039-e819d2b8-ac4d-4d9d-9ec5-6ab22a9c6940.png)

It's probably worth looking for forks where we log the user out to see if there's an error we're catching that logs the user out, or just try and improve logging across the board.

**Comment by seriouslysean** [comment]
Hahahaha, I know what this is now. It has to do with out session destroy logic as far as I can tell. To reproduce:
- Load homepage
- Login
- See game list
- Logout
- Login
- See error (it's a 403, I modified the error to see what was happening)

![image](https://user-images.githubusercontent.com/414475/194391630-868f7328-d248-4a8c-89d9-b74352a7826b.png)

**Comment by seriouslysean** [comment]
Yep, I got it, check this out:
1. initial load I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8` (initial value)
2. On login, I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8` (same value)
3. On logout, I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8` (same value, this needs to be deleted 😎)
4. On relogin, I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8`
5. On reload, I get `s%3AEVw6BGnlugAXdl5DJXYvLTa_do8D1rKj.yYgV4FnF7XNT1yvvd8cyBeg7g5RJ84%2Fm31HCbFwZMhk` (different value)

We need to handle cookie deletion properly.
