### ISSUE TITLE
Refactor updateGame to reduce complexity

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#126]
### Summary

Refactor `updateGame` in two two more more discrete functions

### Detailed Description

`updateGame` in `client/js/store/modules/game.js` currently fires twice when joining a lobby. Once with the full game state which works as expected and updates all the values.

The second call to `updateGame` comes from updating the players and only has the player values. This was noticed when working on the `isRanked` logic. For instance, we currently update values in this way:

```
updateGame(state, newGame) {
  ...
  if (Object.hasOwnProperty.call(newGame, 'isRanked')) state.isRanked = newGame.isRanked;
},
```

We're locking the logic behind the existence of the keys on the object we're passing which means we expect one or more schemas for that `newGame` object. Ideally, this would be refactored to something like this:

- `updateGame` - always takes the full game object so we don't need the `hasOwnProperty` calls and can directly update the state with a set of keys
- `updateGamePlayers` - always takes the players and adds them to the game data
- Other functions may be needed depending on how many ways this function is called and with which payloads

@itsalaidbacklife may have more information here, but this should be enough to do some digging, come up with a plan and then implement an initial pass.

**Comment by itsalaidbacklife** [comment]
See #189 for reworking this to support localization by generating the card text client side
