### ISSUE TITLE
[Bug]: Rules typo - Two's effect should read 'Scrap target Royal or Glasses Eight'

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#127]
### Bug Summary

Currently the two's second one-off effect reads 'Scrap target Royal', but does not mention that two's can scrap glasses eights.

### Detailed Description

See pic
![image](https://user-images.githubusercontent.com/6520704/194599996-528ed1a6-3769-4c05-ba50-7f85db2e5105.png)

The Rules.vue page should be updated so that the second one-off effect for two's reads 'Scrap target Royal or Glasses Eight'.

This should be a matter of updating the `description` field of the object for that move preview, defined on line `384` of `src/client/js/views/Rules.vue` so that it reads

```
            description: 'Twos have two alternative one-off effects: Scrap target Royal or Glasses Eight',
```

### Steps to Reproduce

1. Navigate to the rules page on https://www.cuttle.cards/#/rules or locally at localhost:8080/#/rules
2. Look at the text for the second one-off effect of two's

**Comment by chikaldirick** [comment]
Hey, I've just posted a PR that fixes the typo. Could you, please, check it when you have spare time?
https://github.com/cuttle-cards/cuttle/pull/137
