### ISSUE TITLE
[Feature]: Improve feature request/improvement/bug entry

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#130]
### Feature Summary

Features a little limiting, what about other categories?

### Detailed Description

We probably need to make Feature a little more generic, or add new types like "Enhancement" (think tech debt/refactor) and then maybe a fallback option if it doesn't fit anywhere else.

**Comment by itsalaidbacklife** [comment]
I think this is resolved now that we have the dev experience issue template + label. Features are user facing, so are bugs, and then we have devX for the rest
