### ISSUE TITLE
Add Discord link to GitHub Readme

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#132]
### Feature Summary

More ways to join the community, maybe a discord button

### Detailed Description

https://discord.gg/9vrAZ8xGyh

Maybe a button image added to the repo, too.

**Comment by Tiansing** [comment]
I can work with this.

**Comment by seriouslysean** [comment]
@Tiansing tgst would be great! Use the link above and either add a text link next to the site links under the logo or a standalone “join button”. See what looks better!

Let me know if you have any questions getting to and running!

**Comment by Tiansing** [comment]
@seriouslysean can I have the discord server ID? in order for me to create the discord button

**Comment by Tiansing** [comment]
Hi @seriouslysean , I'm the one who's assigned to add discord link to Github Readme and I just want to request, if you are able to enable the server widget under server settings?  something like this:
![image](https://user-images.githubusercontent.com/59194525/194810856-4f435367-b8f8-4e2c-a4c7-0ab877233b30.png)

for me to create the discord button similar to this:
![image](https://user-images.githubusercontent.com/59194525/194811071-a2ac35ac-9a4c-408e-b939-aef1abed2ce3.png)

**Comment by Tiansing** [comment]
@seriouslysean I have created a new PR #146 Thank you

**Comment by itsalaidbacklife** [comment]
Closed by #146
