### ISSUE TITLE
[Feature]: Improve mobile view for game list

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#133]
### Feature Summary

Various improvements to improve layout on mobile

### Detailed Description

* fix title
* Full width game view
* Move buttons below, 3 across maybe? Might make more sense stacked 1 on top of the other
* potentially move logo to the top

![D2C5D6D9-99EF-41A2-8318-D3585EDCED55](https://user-images.githubusercontent.com/414475/194678386-150381e9-37a6-403e-b93e-aa88c57f28bd.jpeg)

**Comment by vilasrhegde** [comment]
@seriouslysean can I work on this issue?

**Comment by Naveen-Nair** [comment]
@seriouslysean Hey! I would like to work on this issue
