### ISSUE TITLE
[Feature]: Remove collapse feature from Navigation Drawer

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#134]
### Feature Summary

Left swipe hides the navigation drawer on mobile. We should remove the collapse functionality and always use the full size nav on desktop and the collapsed size on mobile.

From @itsalaidbacklife:
> Actually let’s simplify the overall component by removing the toggle-able feature and just making it small on mobile and big on desktop. Then we don’t need to worry about the expand/collapse button conflicting with the logout button at the bottom of the drawer and generally the whole thing will be less complex.

> This way we can remove the click handling functionality and the entire button for expand/collapse, and skip the associated data variable userHasCollapsed along with the isCollapsed computed prop. We can just use the breakpoint.

### Detailed Description

![cuttle-hide-menu](https://user-images.githubusercontent.com/414475/194679328-541d7752-4c45-4687-aeaa-10a430de52fd.gif)

**Comment by singhkaran202** [comment]
I'd love to work on this if that's OK. @seriouslysean, Please assign me this issue.....

**Comment by seriouslysean** [comment]
@singhkaran202 by all means, would love to have you! Try following the project setup, https://github.com/cuttle-cards/cuttle#project-setup-and-development, to see if you can get this running locally.

We use Vuetify 2 for the general layout so you might need to dig through their docs a bit to make sure you’re using the right syntax. https://vuetifyjs.com/en/components/grids/

Reach out in the #coding channel of our discord if you need help, https://discord.gg/9vrAZ8xGyh, and come try out Cuttle! Or, just ping @itsalaidbacklife, @peterancourt or myself on here and we’ll offer some assistance that way.

Best of luck!

**Comment by singhkaran202** [comment]
Thanks alot!! @seriouslysean
Lessgo 🚀🚀

**Comment by seriouslysean** [comment]
I think this can be solved by adjusting the `isCollapsed()` method in the `NavigationDrawer.vue` component, something like this:
```
isCollapsed() {
  // Always collapse on mobile regardless of user collapse setting
  if (this.isSmallDevice) {
    return true;
  }
  return this.userHasCollapsed;
},
```

**Comment by itsalaidbacklife** [comment]
Actually let’s simplify the overall component by removing the toggle-able feature and just making it small on mobile and big on desktop. Then we don’t need to worry about the expand/collapse button conflicting with the logout button at the bottom of the drawer and generally the whole thing will be less complex.

This way we can remove the click handling functionality and the entire button for expand/collapse, and skip the associated data variable `userHasCollapsed` along with the `isCollapsed` computed prop. We can just use the breakpoint.

@singhkaran202 does that make sense? Thank you for bearing with us. I know it’s a change to the original description but I think the end result will be simpler for devs and for users

**Comment by seriouslysean** [comment]
@itsalaidbacklife makes more sense to me, nice 👍🏼

**Comment by singhkaran202** [comment]
@itsalaidbacklife Yupp, I got that!!

**Comment by itsalaidbacklife** [comment]
Closing because instead we're going to completely remove the nav drawer and replace it with an upper nav bar
