### ISSUE TITLE
[Feature]: Convert gameList to a mapped property

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#136]
### Feature Summary

Instead of manually accessing the store in Home.Vue it should use a vuex mapper

### Detailed Description

https://github.com/cuttle-cards/cuttle/blob/main/client/js/views/Home.vue#L95

Convert `gameList` variable to use `mapState` for the value from vuex instead of raw store access, see https://github.com/cuttle-cards/cuttle/blob/main/client/js/store/modules/gameList.js#L15.

https://vuex.vuejs.org/guide/state.html#getting-vuex-state-into-vue-components

**Comment by racky7** [comment]
@seriouslysean Please assign it to me.

**Comment by chikaldirick** [comment]
Hey, I've just posted a PR that fixes the typo. Could you, please, check it when you have spare time?
https://github.com/cuttle-cards/cuttle/pull/138
