### ISSUE TITLE
[Feature]: Update logo.png to the halloween version

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#142]
### Feature Summary

Player SUBMARINO designed a delightful halloween version of the logo. Let's replace client/js/img/logo.png with this new logo for the month of October.

### Detailed Description

Here is the file:
![Franken_Cuttle_Uttle](https://user-images.githubusercontent.com/6520704/194718736-f47716c6-14a7-4413-8f37-dca131c82c4c.png)

We can just do a straight asset swap for the time being and simply rename the new file logo.png and replace the existing one so that each instance of it in the site is replaced

**Comment by Chitvan14** [comment]
Hi, assign this to me.

**Comment by seriouslysean** [comment]
@Chitvan14 one thing I moved with your commit is that the artboard size between the two assets doesn’t match up so a straight swap won’t work without a new asset.

@itsalaidbacklife we’ll need a new one from SUBMARINO.

![57AFBC22-23CA-4E8E-B803-3F6C0E089D7B](https://user-images.githubusercontent.com/414475/194753156-77e60979-5dc1-4745-8d02-00e9c5aef0c6.jpeg)

**Comment by itsalaidbacklife** [comment]
@seriouslysean what are the required dimensions?

**Comment by itsalaidbacklife** [comment]
Update: The current logo's dimensions are 1222 × 1063. Here is a revised version at nearly the same size. @Chitvan14 Can you work with this one?
![FrankenCuttle_Uttle_Resized](https://user-images.githubusercontent.com/6520704/194772848-a1d50ca5-395e-4925-a700-6ebba7d9a628.png)

**Comment by itsalaidbacklife** [comment]
@Chitvan14 if this is complete, can you open a PR?

**Comment by Chitvan14** [comment]
Done, Please Check.
