### ISSUE TITLE
[Feature]: Add contributors to the readme

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#144]
### Feature Summary

Show off all the people who work on Cuttle

### Detailed Description

Maybe something like this? https://contrib.rocks/preview?repo=cuttle-cards%2Fcuttle

ideally this could be a node script on this repo as a tool to generate a static list, could also be manual. Might be nice to show off with this service to start.

Part of this issue should be to research other repositories and see what they are doing.

**Comment by Pavan-Kamthane** [comment]
Assign Me

**Comment by Pavan-Kamthane** [comment]
Please check PR

**Comment by seriouslysean** [comment]
@Pavan-Kamthane sure thing! Before implementing anything I’d really like to see what other open source repositories are doing to showcase their contributors.

I’ll do some research in my side, too. Once you post some examples or put up a PR @itsalaidbacklife snd I will look at it and make a call as to which style we prefer.

Possibly something like all contributors, https://github.com/all-contributors/all-contributors.

It would be nice to give non coders a chance to be in there, too. We have a lot of people helping in the Discord server, too.

**Comment by seriouslysean** [comment]
There’s also a bot that will handle a lot of it, https://allcontributors.org/docs/en/bot/overview.

I think for the time being a contributors section on the readme might be enough, never hurts to look around though.

**Comment by itsalaidbacklife** [comment]
@seriouslysean pr is drafted (#145)

**Comment by itsalaidbacklife** [comment]
Closed by #145
