### ISSUE TITLE
[Feature]: Update history to use emojis for the card suits

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#147]
### Feature Summary

The text blurb 'Six of Hearts' would become 6♥

### Detailed Description

This would be accomplished by updating the `cardService.createCard` function so that the `name` of each card uses the unicode values for the suits:
![image](https://user-images.githubusercontent.com/6520704/194900513-338a90ef-29f7-4bb6-9b82-f5e14e5b2ceb.png)

Before finalizing, we should check both how the updated card names appear in the History, and each of the Dialogs where card names appear: the `CounterDialog` and the `CannotCounterDialog`

**Comment by byarmis** [comment]
![image](https://user-images.githubusercontent.com/1594170/194980914-03219e93-a776-43c6-94a7-b6bbb36c8a66.png)
![image](https://user-images.githubusercontent.com/1594170/194980968-c100e2af-f294-4162-b839-5d0f267d7244.png)
![image](https://user-images.githubusercontent.com/1594170/194981087-6b3aa14a-146f-4a65-9954-50ff1e79e76b.png)
