### ISSUE TITLE
[Feature]: Leaderboard should break ties in rank based on number of wins

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#155]
### Feature Summary

This is a revision to the Stats page leaderboard. When two players have the same number of points in a given season, the player with more total wins for that season should be given the highest rank. Only if the totals of points and wins are equal should the players be tied for the same rank.

### Detailed Description

In the example below, seriouslysean should be given 8th place because they have fewer total wins (3) compared with ben@yarm.is
![image](https://user-images.githubusercontent.com/6520704/195384919-f7dc4463-b4b4-42b8-aeae-4f6dbf2f9304.png)

This change would be made in the `StatsLeaderboard.vue` component and its `rank()` function to account for the win totals in addition to the point totals.

**Comment by billy-le** [comment]
I'm interested in working on this if no one else is assigned. Thanks!

**Comment by itsalaidbacklife** [comment]
Awesome! Let me know if there's anything I can do to help you set up or to approach this issue. Of course feel free to ask questions in this issue thread, and if you'd like more real-time help/chat, you can use the #code channel of our [discord](https://discord.gg/6vQCFa6nvP) to talk to me or the other devs any time (I'm @aleph_one there)

**Comment by billy-le** [comment]
hi @itsalaidbacklife , is there a way to seed the db with some data?

**Comment by itsalaidbacklife** [comment]
Hi @billy-le, thanks again for checking this out.

Yes its definitely possible to seed data during localhost development. While booted in `development` mode (the default), you can make requests to `/test/loadSeasonFixture` and `/test/loadMatchFixtures` to seed records into those tables.

The easiest (and in my opinion best) way to do it is using test code. If you look at `tests/e2e/specs/out-of-game/stats.spec.js` you'll find the tests for the stats page, which are written using [cypress](https://docs.cypress. io). These tests already import fixture data from `tests/e2e/fixtures/statsFixtures.js` and use a custom cypress command to request those endpoints and seed that data into the database beforeEach test.

I think the best way to go will be to update that `statsFixtures` file's match data so that it it includes a tie in points that's broken by wins ie one player wins week 1 and another wins week 2 but have one or the other player win their week with more match wins than the other.

You can run the tests by booting the server and client and then running `npm run e2e:gui` in a separate terminal. That will open the cypress ui and then you can click the Stats test file to run its tests, which will seed the season and match data then make assertions about the stats page UI

**Comment by billy-le** [comment]
Thanks for that write up @itsalaidbacklife ! It was really helpful. Do you mind if I add a CONTRIBUTING.md and include this part?

**Comment by itsalaidbacklife** [comment]
> Thanks for that write up @itsalaidbacklife ! It was really helpful. Do you mind if I add a CONTRIBUTING.md and include this part?

That would be great! Please submit it in a separate PR. Check out #28 for a starting point

**Comment by itsalaidbacklife** [comment]
Closed by #164
