### ISSUE TITLE
[Feature]: Filter future seasons out from the data sent to the stats page

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#163]
### Feature Summary

Currently the stats page displays all the available Seasons that are listed in the database. We should the backend endpoint that services the stats page to filter out the future seasons (start time is after current time).

### Detailed Description

Currently if seasons are added to the database (e.g. Spades 2023) for a future start time, they will be displayed in the Stats page, and the latest-starting one will be pre-selected in the dropdown at the top of the page like so:
![image](https://user-images.githubusercontent.com/6520704/195924595-fcd8db58-58de-432e-b6e1-812dd3532537.png)

This is unideal from a maintenance standpoint because it means we need to wait until the end of the previous season to add the new one to the database. It would be much more efficient to have the backend endpoint that generates the stats payload to filter out the seasons that haven't started yet. That way we could add future seasons in one big batch without worrying about waiting until just before they start.

To do this we should update `api/helpers/get-seasons-without-rankings.js` which is a helper used to fetch the seasons. In that function, the query for all the seasons should receive an additional `where` clause to filter down to the seasons that are only have a start time that is less than the current time. See line 7 of that function:
```
const seasons = await Season.find({ sort: 'startTime DESC' }).populateAll(); // this should update to set the `where` inside the .find()
```
The where clause can be set according to the [sails docs on querying](https://sailsjs.com/documentation/concepts/models-and-orm/query-language) and the current time should be calculated using `dayjs().valueOf()` ([docs](https://day.js.org/docs/en/display/unix-timestamp-milliseconds)) which should compute the current time in milliseconds

**Comment by P-DR0ZD** [comment]
Can I work on this @itsalaidbacklife

**Comment by itsalaidbacklife** [comment]
@P-DR0ZD Yes please do! Please feel free to ask any questions you have here or in discord
