### ISSUE TITLE
[Bug]: Cards in opponent's hand spin when the opponent draws

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#171]
### Bug Summary

Because we are shuffling the card in the opponent's hand to prevent tracking which card the opponent plays/leaves in their hand, the cards get re-rendered and re-transformed when the opponent draws, causing them to spin

### Detailed Description

This is likely because of this change
![image](https://user-images.githubusercontent.com/6520704/196067116-276e5460-4b55-4608-b485-6aa13e187924.png)

in #157. Previously the entire opponent hand was rotated, but now it's the individual cards, causing the css rotate transform to apply every time a new card is drawn

**Comment by jerryh-jr** [comment]
@itsalaidbacklife will work on this one.
