### ISSUE TITLE
Jacks and Deck Cards (during 7) are small in Firefox

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#179]
### Bug Summary

We recently switched the card images to .svg’s which need an explicit size set. It is likely that the jacks and the deck cards during 7 resolution are missing that explicit size

### Detailed Description

Cared images of jacks and of the cards in the deck display very small or even I fail to display on Firefox 

### Steps to Reproduce

1. Open the app in Firefox 
2. Play a jack or a 7
3. See the cards fail to load or load too small

**Comment by thomasjvu** [comment]
Hi there! I'd like to work on this issue if possible.
