### ISSUE TITLE
[Bug]: When resolving a 7, choosing a move that targets and then canceling and selecting the other card leaves you still targeting.

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#186]
### Bug Summary

We fail to clear out the targeting state when you cancel the decision to make a play that targets from the top of the deck

### Detailed Description

When you play a 7 you get to pick one of the top two cards of the deck to play. Then you can click a card, and you'll be presented with the options of how to play it. If you pick a jack, or the one-off effect of a 9 or two, you'll be presented with another UI for choosing which card to target. 

That UI doesn't properly go away if you cancel the decision to play that 9/jack/2, and then click another card. To fix this we should create a test case in `e2e/specs/in-game/sevens.spec.js` and then examine the function that cancels targeting to ensure it properly resets its state

### Steps to Reproduce

1. Opponent should have a point card out
2. There should be a 9, 2, or jack on top of the deck
3. Play a 7
4. Click a 2, 9, or jack off the top of the deck and choose to play its targeting effect (one-off or royal)
5. Click 'Cancel'
6. Click the **other** card on the top of the deck
Expected behavior is that you will see the options to play your move as normal, but instead currently you'll see the targeting overlay

**Comment by TommySchmid** [comment]
I'll be working on this one

**Comment by itsalaidbacklife** [comment]
@TommySchmid verified that this is no longer reproducible. Closing until further notice
