### ISSUE TITLE
[DevEx]: Refactor layout.spec.js to skip aesthetic-only tests

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#192]
### Improvement Summary

layout.spec.js includes a few logical tests but also aesthetic ones for the purpose of easily seeing how the game looks with many cards on the field etc

### Detailed Description

Most of the tests in tests/e2e/in-game/layout.spec.js don't actually make useful assertions; they are just there to quickly load the game into a state to see how it looks when there are many cards on the field etc at various viewports.

That's fine, but there's no need to run these tests in CI because they don't add confidence. These tests should be separated from the rest within that file into their own describe block and skipped e.g.  describe.skip('Aesthetic tests') so they can be used during development but don't clutter up CI.

Note that some tests like it('Hides navbar on gameview page', () => { are actually useful for asserting application functionality and should be kept in CI scope

**Comment by Myrfion** [comment]
Hi, could I take this one?

**Comment by itsalaidbacklife** [comment]
@Myrfion yes, thank you! Please feel free to ask any questions here if you'd like help setting up or approaching the issue

**Comment by Myrfion** [comment]
@itsalaidbacklife created the PR :)
