### ISSUE TITLE
[DevEx]: Replace vue-cli with vite

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#195]
### Improvement Summary

[Vite](https://vitejs.dev/) is the current build tool recommended for vue development. We should replace the deprecated vue-cli with vite.

### Detailed Description

This relates to the vue3 update as well. We will need to unravel the prerequisites to sequence this correctly with the typescript and vue3 todos. See  #193 and #114

**Comment by seriouslysean** [comment]
Done :)
