### ISSUE TITLE
[Feature]: Update Stats leaderboard menu to include win rate

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#201]
### Feature Summary

When you click a cell in the StatsLeaderboard, you see a menu with all the players who won and lost agains the selected player in the selected week. We should update this menu to additionally include the win rate at the bottom of that menu

### Detailed Description

Here is the menu in question:
![0DE86CA5-D993-44D8-A3F7-8FE09F24B277](https://user-images.githubusercontent.com/6520704/198881109-b429f87c-5b96-4083-9d5d-f0c1636f755e.png)

We should include a third section, “Win Rate” below “Wins” and “Losses”, at the bottom of this menu. Which displays the % of completed matches in the relevant week (or total for the total column) that the selected player won.

The relevant file is `client/js/components/StatsLeaderboardCell.vue` 

In addition, the header on this menu should be adjusted to specify which player’s results we are viewing for which week. So instead of simply saying “Results”, the header should read “[username] Week [week_number] Results” e.g. “aleph_one Week 3 Results”. When viewing a menu for the total column, it should use the season name instead e.g. “ aleph_one Spades 2022 Results”

**Comment by franciscoemanuel** [comment]
@itsalaidbacklife Working on it!

**Comment by itsalaidbacklife** [comment]
@franciscoemanuel excellent; thank you! Let me know if you have any questions or need help setting up
