### ISSUE TITLE
[Bug]: Cards in ThreeDialog are unclickably small in Firefox

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#206]
### Bug Summary

When using firefox, the cards in the ThreeDialog are very small to the point of being unclickable

### Detailed Description

This is likely due to missing an explicit size on the images which have been changed to `.svg` files. See #179

**Comment by jerryh-jr** [comment]
@itsalaidbacklife is this one you wanted to assign to me?

**Comment by itsalaidbacklife** [comment]
Yeah @jerryh-jr can you have at it?

**Comment by jerryh-jr** [comment]
@itsalaidbacklife sure can. Will work on it tonight.
