### ISSUE TITLE
[DevEx]: Enable debugging the backend by default

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#208]
### Improvement Summary

Debugging nodejs servers requires booting them with the --inspect option. We should make this the default for localhost development of the backend

### Detailed Description

We should update the backend-booting scripts of package.json to this effect. In particular, the `start:dev` and `start:server` commands should be updated to include the `--inspect` flag applied to the `node app.js` part of the command.

This will enable us to use VSCode's `Debug: Attach to node process` command to debug the backend, placing points on the relevant lines and stepping in and over function calls while viewing all the variables as you'd expect.

We should additionally update the README with a section on debugging the backend server that explains to use a node debugger like the one in vscode, and explaining that to use vscode's debugger, hit cmd+shift+p or ctrl+shift+p and then use the `Debug:attach to node process` at which point you can click any line number in backend code to add a breakpoint to it, and use the variable inspector to view the variable state etc

**Comment by cychu42** [comment]
Hi, I wish to work on this.

**Comment by itsalaidbacklife** [comment]
@cychu42 excellent, thank you! Please let me know if you have any questions, would like help setting up, or to discuss the issue further. 

You can comment here in the issue thread for async updates/Q&A, or if you use discord, you can ask questions in the #code channel of [our server](https://discord.gg/tPWm6kpbmb) for to chat with me other devs in real time. Thanks again for your help!

**Comment by cychu42** [comment]
Alright. Thank you!
