### ISSUE TITLE
[Feature]: realign the count of cards in the deck so it doesn’t touch the edge of the deck

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#231]
### Feature Summary

The deck has a text blurb with the count of how many cards are in it, but it is awkwardly placed all the way at the bottom so it’s flush with the bottom of the deck. We should move it slightly upwards so there is a margin between the text and the bottom edge of the dexk

### Detailed Description

The (1) in the picture should be moved slightly upwards.

**Comment by itsalaidbacklife** [comment]
![Uploading 4FCB761E-A988-4823-A413-105CD8671242.png…]()

**Comment by itsalaidbacklife** [comment]
@gulyapulya Thank you!
I'll re-upload the image for reference:
![image](https://user-images.githubusercontent.com/6520704/205729334-58b1a9dd-7003-45fb-85d4-8be7031a125d.png)

This style is controlled in `client/js/views/GameView.vue`.

You can look at the `<v-card>` html on lines 133-167 for where the deck is defined, and styles are at the bottom of that file

**Comment by gulyapulya** [comment]
Hi, thanks a lot, I think adding margins to the c-deck-count should do the job, as it is the class controlling the count number. I am trying to make it work locally to test the change. I have the site working at localhost but I am not sure how to initiate the game as I cannot sign up twice - it just changes my username, could you help me with the steps to reproduce it?
