### ISSUE TITLE
[Feature]: [Bug]: Limit the length of the name of games 

### ISSUE THREAD

**Issue by byarmis** [cuttle-cards/cuttle#251]
### Feature Summary

Limit the length of the name of games 

### Detailed Description

![image](https://user-images.githubusercontent.com/1594170/207753799-84be5341-41f2-4539-9caa-c04515f60c96.png)

I dunno what it should be, but shorter than this

**Comment by TommySchmid** [comment]
Im going to be taking a look at this one.

**Comment by TommySchmid** [comment]
Issue resolved in `feature/vue3` branch - https://github.com/cuttle-cards/cuttle/commit/717a90d6f934b9a5df2a47b3f6d121df2fbbc5bb

**Comment by seriouslysean** [comment]
Looks like this was resolved.
