### ISSUE TITLE
[DevEx]: Fix failing sevens.spec tests

### ISSUE THREAD

**Issue by TommySchmid** [cuttle-cards/cuttle#266]
### Improvement Summary

We should fix all failing automated tests

### Detailed Description

Vue3 updates have broken multiple sevens tests which need to be examined and updated.

These tests fail when the `waiting-for-opponent-to-counter-scrim` overlay should be displayed - likely related to the following

1. we don't need to emit 'click' events from child components anymore -- vue is doing this automatically
2. v-model was changed so the child component needs a prop called modelValue not model

Failing test are marked `.skip`.

**Comment by itsalaidbacklife** [comment]
I'm working on this

**Comment by itsalaidbacklife** [comment]
#293
