### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by seriouslysean** [cuttle-cards/cuttle#28]
Maybe outline any sort of code quality concerns, etc in this file to set expectations for contributors?
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

I really like the open government template, might be worth looking at as an example, https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md.

**Comment by itsalaidbacklife** [comment]
Closed by #165
