### ISSUE TITLE
[Feature]: Stats Page - Enable creating a link to a specific season's leaderboard

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#281]
### Feature Summary

Currently the Stats page uses internal data/variables to manage which season is currently selected. It would be better if the selection were managed via a url param, so that you could then copy the url and send it to someone, bringing them directly to the season you were looking at when you copied the url.

### Detailed Description

Notice how these two seasons both have the same url: https://cuttle.cards/#/stats
![image](https://user-images.githubusercontent.com/6520704/212693983-c5bad828-74ab-43f2-a5d4-97ac780af8e8.png)

![image](https://user-images.githubusercontent.com/6520704/212694082-e4446234-65e3-46e4-ae60-9104dc886790.png)

If you send someone the url https://cuttle.cards/#/stats, they will always be brought to the latest season. It would be better if you could specifically link someone to the Spades 2022 season with a url like https://www.cuttle.cards/#/stats?seasonIndex=3

This season index should be loaded from the url when the page is created, and it should be updated whenever the dropdown is used to select another season. All of the changes should be doable using only src/client/js/views/Stats.vue

**Comment by shikevin7** [comment]
@itsalaidbacklife I'll attempt to look into this!

**Comment by Haviles04** [comment]
Working on this!
