### ISSUE TITLE
[Bug]: Your Turn and Goal get covered by your hand on small devices

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#334]
### Bug Summary

See pic. The text displaying whether it's your turn and your point goal + total is covered up behind your hand

### Detailed Description

Image taken on mobile (galaxy A13) in landscape mode
![image](https://user-images.githubusercontent.com/6520704/218535910-e05f9578-5038-4aba-b24f-fc97f4727762.png)

We should adjust this so that the text consistently appears above the hand but below your cards in play. 

### Steps to Reproduce

1.
2.
3.

**Comment by Haviles04** [comment]
Taking a look at this!
