### ISSUE TITLE
[BUG]: Backend allows subscribing to closed games

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#346]
### Bug Summary

When a game becomes full (has 2 players) the frontend disables the join button for that game, but the backend still accepts requests to subscribe to it

### Detailed Description

The /game/subscribe endpoint makes no check that the game is open for players to join. Currently users are prevented from subscribing to games client side, but we should also prevent this on the backend.

Basically this endpoint should query for the game being requested *before* subscribing you to it, and should return a badRequest response if that game has a `status === false` or if the number of players it has is > 1. 

The frontend should then show a snackbar when this error occurs 

### Current Behavior

If you remove the `disabled` prop from the join button in `GameListItem.Vue` and create a game, join it as two players then try to join it as a third player, it will bring the new player to the lobby of the game and add them to the list of players, causing weird effects in the game.

### Expected Behavior

When a user attempts to join a game that’s closed or that has two players in it already, the backend should throw an error that’s displayed in a snackbar to the user saying “Oops, that game is already full”

### Steps to Reproduce

1. Remove the `disabled` prop from `GameListItem.Vue`
2. Start the front and back ends, sign up three accounts in three separate browsers
3. Create a game, and join it as two players
4. Join it as the third player and you will be incorrectly brought to the lobby

**Comment by TommySchmid** [comment]
I'll be taking a look at this issue.

**Comment by shikevin7** [comment]
Hello, if this issue is still open, I was hoping to get some guidance on which files to look at in order to make these changes? Thanks!

**Comment by TommySchmid** [comment]
Hey there @shikevin7 ! 

I've already started working on this issue; I'd be happy to fill you in on how I end up implementing a fix, but for the time being I'd suggest selecting another issue to look at from the backlog - https://github.com/cuttle-cards/cuttle/issues

**Comment by TommySchmid** [comment]
Hi @shikevin7 ! - As it happens, I've not been able to find the time to work on this issue, so i'd rather not keep you from digging in. Feel free to jump on it if you'd like.

As far as which files to start with - it looks like the `requestSubscribe` action within `game.js` file is responsible for adding players to a game lobby. Adding some sort of check there to see if two players are already in the lobby might be a good place to start. 

You've already joined the Discord (awesome!) - Feel free to post any questions you have in the #code channel.

**Comment by shikevin7** [comment]
Hello @TommySchmid! I apologize for the late response but thank you for your advice! I will attempt to look into it but will also keep an open mind about other issues from the backlog :)

**Comment by shikevin7** [comment]
I was hoping to test my patch for the bug, but I can't seem to find the join button for subscribing. Can someone point me in the right direction?

**Comment by shikevin7** [comment]
Hi @TommySchmid! I attempted to make the patch but am now struggling to understand how to create a test case for it. In addition, I'm not sure if I am going about this patch the right way. I feel like I might be a little in over my head with this assignment so definitely feel free to take this issue from me if you would like :)

**Comment by itsalaidbacklife** [comment]
Submitted #403 to address this
