### ISSUE TITLE
[Bug]: Gameover dialog flickers to loss before going home

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#348]
### Bug Summary

When you click the 'Go Home' button from the GameOverDialog, the dialog quickly flickers to show 'You Lose' before navigating home

### Detailed Description

See gif:
![Gameover dialog flicker](https://user-images.githubusercontent.com/6520704/223443052-ce784272-e639-4b6d-bfc4-a924c1fda7b8.gif)

This is likely a result of clearing the store state before navigating to the home page

### Steps to Reproduce

1.
2.
3.

**Comment by Haviles04** [comment]
I'd like to work on this!

**Comment by itsalaidbacklife** [comment]
Great! Hopefully the CONTRIBUTING.md file will have everything you need to set up, but feel free to ask any questions about setup or the bug itself here in the comments of this issue. Or if you're on discord, you can reach out on the [cuttle server](https://discord.gg/zZujC7Tp5j) to chat with the other devs in realtime in the #code channel
