### ISSUE TITLE
[Feature]: Blast 'gameFinished' socket event when games end due to offensive play, passing, or stalemate request

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#354]
### Feature Summary

When a game finishes, it is no longer available to spectate. This is prevented on the backend but we should also disable the 'Spectate' button on the game in the HomeView page.

### Detailed Description

There is already frontend setup to handle disabling a game when an event comes in to register that it is finished: the backend just needs to emit a 'gameFinished' event like so:

```
// see api/controllers/game/concede.js
sails.sockets.blast('gameFinished', { gameId: game.id });
```

As shown above, this already works when a player concedes. To apply this for the other ways that games can end, we should add the same line into the parts of the other backend actions that can end the game: passing, requesting a stalemate, or calculating that the game is over due to an offensive play:
1. `api/controllers/game/pass.js`
2. `api/controllers/game/stalemate.js`
3. `api/controllers/services/gameService.js` -- `checkWinGame()` function

When this works, it will result in the 'Spectate' button disabling for those games if you are on the HomeView before the game finishes. We should update the specatating `describe()` block in the `tests/e2e/specs/out-of-game/home.spec.js` tests to check these cases when we fix them.

**Comment by Haviles04** [comment]
I'm working on this one!
