### ISSUE TITLE
[Bug]: Fix StatsScoringDialog's reference to the championship tournaments

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#355]
### Bug Summary

The StatsScoringDialog has out of date text and could use some style updates

### Detailed Description

See this annotated image with requested changes. Involves:
1. Switching the button type of the cancel button
2. Adding vertical margin between the top text and the AwardCard's
3. Updating the text at the top and bottom to say 'top 8 players' instead of top 4
4. Adding a sentence about the World Championship

![image](https://user-images.githubusercontent.com/6520704/224726403-cd6d27ec-1581-45d3-94f3-5fb834a81620.png)

All of these changes could be implemented in the `src/components/StatsScoringDialog.vue`

### Steps to Reproduce

1. Navigate to the stats page at https://cuttle.cards/#/stats
2. Click the 'How are Ranks Determined' button
3. Dialog will appear and will have the problems outlined above

**Comment by Haviles04** [comment]
I'd like to take this one!
