### ISSUE TITLE
[Bug]: Looking to Play section of Homepage is incorrectly styled

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#357]
### Bug Summary

The 'Looking to Play?' section of the HomeView has no padding that separates it from the list of games. This looks visually awkward.

### Detailed Description

See image.
![image](https://user-images.githubusercontent.com/6520704/225904292-5db35b70-6a5d-4129-a3db-18b8c3e06d17.png)

More precisely, the padding exists on the parent element containing the logo and buttons, but seems to be ignored by the `<ul>` element with the bullet points and the event times.

We should clean this up so that bullet points left-align with the rest of the content, rather than the text left-aligning with the content. This will create more space between the bullets and the list of games, which will look better

### Steps to Reproduce

1. Sign up or log into app on desktop
2. Look at the 'Looking to Play?' section's bulleted list

**Comment by omernadeem1070** [comment]
Hello, I would like to take care of this. Thank you.

**Comment by itsalaidbacklife** [comment]
> Hello, I would like to take care of this. Thank you.

Great, thank you! If you have any questions about setup or implementation, please feel free to ask them here. Or if you use discord, you can use the #code channel of our [server](https://discord.gg/6vQCFa6nvP) to chat with the devs in real-time.
