### ISSUE TITLE
[DevEx]: Add Troubleshooting section to CONTRIBUTING.md

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#359]
### Improvement Summary

In order to make it easier for new contributors to set up, we should add a Troubleshooting section to the CONTRIBUTING.md doc

### Detailed Description

To start, this could include two issues:

1. Setting up on Windows 11 (which could recommend the use of Windows Subsystem Linux)
2. Cypress not running on Ubuntu (which can link to the [cypress installation prerequisites](https://docs.cypress.io/guides/getting-started/installing-cypress#Linux-Prerequisites) and recommend running the command 
```
apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
```

We can add to this section as further issues arise, to answer common questions/address common problems

**Comment by Haviles04** [comment]
Got this!
