### ISSUE TITLE
[Feature]: Sound notification for lobbys

### ISSUE THREAD

**Issue by DonPierreDon** [cuttle-cards/cuttle#364]
### Feature Summary

Add sound design for enter/leave lobby.

### Detailed Description

It would be nice to have an indication that someone join your lobby even if you are not currently on the webpage, to do so adding a different sound for when someone enters the room and leaves the room would be great.

**Comment by DonPierreDon** [comment]
I am working on it.

**Comment by itsalaidbacklife** [comment]
Resolved by #371
