### ISSUE TITLE
[DevEx]: Implement Logging Service

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#368]
### Improvement Summary

In order to have more flexible access to console logs and error management, we should implement a 3rd party logging service

### Detailed Description

This would enable us to more easily sift through logs to identify patterns in errors or other issues. It could also allow us to define specific errors that we can more easily see in the logs via filtering. The initial implementation should log uncaught serverside errors.

**Comment by seriouslysean** [comment]
https://www.rollbar.com/
