### ISSUE TITLE
[Feature]: Apply the new BaseDialog colors & styles (chocolate and cream) to the out-of-game dialogs

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#395]
### Feature Summary

#389 revised all the in-game dialogs by defining a new BaseDialog component that the dialogs in the game consume to standardize their look and feel. Now we should update the styles of the out-of-game dialogs e.g. CreateGameDialog to match

### Detailed Description

This is the style of our new in-game dialogs:
![image](https://user-images.githubusercontent.com/6520704/233648348-7f620890-6e32-4241-b202-8ba778a9acf3.png)

They use the surface-1 (chocolate) and surface-2 (cream) colors from our client/plugins/vuetify.js theme definition. 

The following dialogs in the application do not yet use the BaseDialog component and therefore have a bland black and white look that doesn't match the application:

1. CreateGameDialog
2. RulesDialog
3. StatsScoringDialog

Here's how the CreateGameDialog looks, for comparison
![image](https://user-images.githubusercontent.com/6520704/233648933-cda41214-3d49-4153-9736-29018b3fc627.png)

Updating these remaining dialogs will improve the look and feel of the application and give users a better and more coherent sense for the brand of the site.

For implementation, look at the definition of the `client/components/Global/BaseDialog.vue` component and look at how it is used in the FourDialog to see how to apply it in these remaining three out-of-game dialogs. Notably:

1. id and title (the heading) are set via props
2. The dialog body is set via a template tag filling the #body slot (`<template #body></template>`)
3. The dialog buttons are set via a template tag filling the #actions slot (`<template #actions></template>`)

**Comment by DonPierreDon** [comment]
I would like to take this one
