### ISSUE TITLE
[Bug]: Navigating to the url of a completed game gives you a blank background image

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#405]
### Bug Summary

Navigating to a game url for a game that's over currently causes an uncaught error and leaves the user stuck on a dead page. We should detect this error and instead open a dialog that invites the user to navigate home.

### Detailed Description

Navigating to a completed game url like /#/game/1 currently causes an error that leaves the user on a blank page like this:
![image](https://user-images.githubusercontent.com/6520704/236852153-fcdcbc61-d7fe-4a64-a831-4abb5f46a893.png)

We should fix this so that users instead get a dialog that explains that this game is over and that they should go home, with a button to bring them to the home screen

### Current Behavior

The blank screen appears

### Expected Behavior

A dialog appears with:

Title: Oops!
Body: This game is over, nothing to see here
Actions: Button that says Go Home which behaves the same as the GameOverDialog's Go Home button

### Steps to Reproduce

1. Sign up and start a game with two players
2. End the game (by playing it out, conceding etc)
3. Wait for the GameOver dialog to appear and refresh the page
4. You'll see this screen
5. 
![image](https://user-images.githubusercontent.com/6520704/236852470-23ddf0b8-4a1b-4bbb-9a99-407a7a424738.png)

**Comment by Haviles04** [comment]
I'll take this!
