### ISSUE TITLE
[DevEx]: Update linting config to limit html to 3 attributes in a single line

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#415]
### Improvement Summary

We should make the line-lengths of html content more consistent by enforcing lint rules regarding the number of attributes per line and where they should go.

### Detailed Description

The convention we've roughly followed for formatting html is as follows:
1. All attributes can go on a single line if there are <= 3 attributes
2. Otherwise it should go on multiple lines, with one line per attribute

Example:

```
  <!-- ✓ GOOD -->
  <MyComponent lorem="1"/>
  <MyComponent lorem="1" ipsum="2"/>
  <MyComponent
    lorem="1"
    ipsum="2"
    something="3"
    else="4"
  />

  <!-- ✗ BAD -->
  <MyComponent lorem="1"
               ipsum="2"/>
  <MyComponent lorem="1" ipsum="2" something="3" else="4" />
```

To configure this app-wide in an auto-fixable manner, we should use the vue eslint rules [max-attributes-per-line](https://eslint.vuejs.org/rules/max-attributes-per-line.html) and [first-attribute-line-break](https://eslint.vuejs.org/rules/first-attribute-linebreak.html).

We should set the max-attributes-per-line to `singleline: 3` and `multiline: 1` so that we allow up to 3 attributes when the entire component is in one-line and we only allow one attribute per line when breaking into multiple lines.

Then we should confvigure first-attribute-line-break to `singleline: "beside"` and `multiline: "below"` so that when all the attributes fit on a single line, they go next to the tag, and when they fit on multiple lines, they each go below.

These two rules together should enforce the style we've been using informally but in a way that will apply consistently across the entire app. In addition to configuring the rules as described, we'll need to format the code with `npm run lint:fix` to fix any violations of these rules app-wide.

**Comment by JaiS99** [comment]
Clarification Needed: 
These two rules, will also affect other things, like every line that has more than three attributes will have all attributes split up, in some cases this might not be the effect that you wanted. Do you still want to proceed with this?

**Comment by itsalaidbacklife** [comment]
> Clarification Needed: 
> 
> These two rules, will also affect other things, like every line that has more than three attributes will have all attributes split up, in some cases this might not be the effect that you wanted. Do you still want to proceed with this?
> 
> 

Yes the intent is to require that a single line of html can have no more than 3 attributes, and tags with 4+ attributes be split into one line per attribute, so this 

```
<!-- ✗ BAD -->
<MyComponent lorem="1" ipsum="2" something="3" else="4" />
```

becomes this:
```
  <!-- ✓ GOOD -->
  <MyComponent
    lorem="1"
    ipsum="2"
    something="3"
    else="4"
  />
```

Whereas for tags with 3 or fewer attributes we'd allow them in a single line like so:

```
<MyComponent lorem="1" ipsum="2"/>
```

We have roughly used this style already but it hasn't been automatically (and therefore consistently) enforced. 

Does that answer your question? Is there another side effect of this change beyond what I've mentioned here that you think may be undesirable?

**Comment by JaiS99** [comment]
Yes, Refer to PR #416 

> > Clarification Needed:
> > These two rules, will also affect other things, like every line that has more than three attributes will have all attributes split up, in some cases this might not be the effect that you wanted. Do you still want to proceed with this?
> 
> Yes the intent is to require that a single line of html can have no more than 3 attributes, and tags with 4+ attributes be split into one line per attribute, so this
> 
> ```
> 
> <MyComponent lorem="1" ipsum="2" something="3" else="4" />
> ```
> 
> becomes this:
> 
> ```
>   
>   <MyComponent
>     lorem="1"
>     ipsum="2"
>     something="3"
>     else="4"
>   />
> ```
> 
> Whereas for tags with 3 or fewer attributes we'd allow them in a single line like so:
> 
> ```
> <MyComponent lorem="1" ipsum="2"/>
> ```
> 
> We have roughly used this style already but it hasn't been automatically (and therefore consistently) enforced.
> 
> Does that answer your question? Is there another side effect of this change beyond what I've mentioned here that you think may be undesirable?

Refer PR #416 for changes, unfortunately, my device will not support, electron, need someone to take it and actually check the effect from here, making sure all the test cases are passing.

**Comment by JaiS99** [comment]
they can run the Lint fix in my fork before making changes.

**Comment by itsalaidbacklife** [comment]
> they can run the Lint fix in my fork before making changes.
> 
> 

The tests will be run in CI so that will confirm that there are no regressions. You can run `npm run lint:fix` to auto fix the linting errors. That shouldn't require electron, and then the cypress tests will run in GitHub actions after you push
