### ISSUE TITLE
[Bug]: Resolving one-offs doesn't clear the player's frozen card

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#433]
### Bug Summary

Playing an untargeted one-off (a 2 or a 9) on an opponent's card in play doesn't correctly unfreeze the cards in your hand.

### Detailed Description

When your opponent plays a 9 on one of your cards that card can't be played on your next turn. Making any move is supposed to 'unfreeze' the card in your hand so that it's playable again. This doesn't work correctly if your next move is to play a targeted one-off.

If your next move after your opponent returns one of your cards to your hand is to play a targeted one-off i.e. a 2 or a 9, the card that your opponent returned to your hand remains frozen the next turn. 

Addressing this issue requires 1) a test case and 2) a code fix
The test case should live in the `one-offs.spec.js` test file inside the existing `describe()` block for 9's and essentially 
1. Setup the game as P1
2. Load a game fixture so both players have a king on the board, and a 9 in hand
3. Have the opponent play a 9 one-off on the player's king
4. Have the player play a 9 one-off on the opponent's king
5. Have the opponent draw a card
6. Have the player attempt to play the king that was returned to their hand
7. Assert the expected game state where the 9 was successfully played

The fix should live in `api/controllers/game/targeted-one-off.js` which handles playing 9's and 2's. Whether a card is frozen in the player hand is controlled via a `frozenId` variable on the users with the frozen card. We need to set that value to `null` when playing a targeted one-off. Essentially it should mirror the setup in the complimentary `api/controllers/game/untargeted-one-off.js` file, where we declare a variable to define the `playerUpdate` and then make an update call which persists that change to the database like
```
// This variable needs to be added to define the change
const playerUpdates = {
  frozenId: null,
};
const updatePromises = [
  Game.updateOne(game.id).set(gameUpdates),
  User.removeFromCollection(player.id, 'hand').members([card.id]),
  User.updateOne(player.id).set(playerUpdates), // adding this to the existing update promises will persist the change
];
```

**Cleanup**
In addition to the fix itself, we should remove two stale lines from `api/controllers/game/resolve.js` which are about the same issue but are not actually used:
```
      const playerUpdates = {};
```
and
```
        playerUpdates.frozenId = null;
```
are both unnecessary as the `playerUpdates` variable isn't actually used. The two lines above can be deleted as a part of the fix.

### Current Behavior

The card that your opponent returns to your hand becomes unfrozen after you play a 2 or 9 the next turn.

### Expected Behavior

The card that your opponent returned to your hand remains frozen after you play a 2 or 9.

### Steps to Reproduce

1. Start a game
2. Play a point card or royal
3. Have your opponent play a point card or royal
4. Have your opponent play a 9 to return the card to your hand (resolve it)
5. Play a 9 on your opponent's point card to return it to _their hand_
6. Have your opponent resolve your 9
7. Have your opponent make any move
8. You _should_ now be able to play the card that was previously frozen in your hand, but it remains frozen

**Comment by Haviles04** [comment]
I'm going to take a look at this.
