### ISSUE TITLE
[DevX]: update PR template to say “resolves” in from of the issue number

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#437]
### Improvement Summary

In order for a PR to automatically close the associated issue, the PR description must use a phrase like “Resolves #76”. The PR template currently has an affordance to add the PR number but it also needs to add the word “Resplves” in front of the issue number for the issues to close automatically.

### Detailed Description

We should update `.github/PULL_REQUEST_TEMPLATE.md` so the top paragraph reads: 
```
Relevant issue number (e.g. #404): Resolves #
```

**Comment by karthickbharathi1** [comment]
Hey @itsalaidbacklife can you assign this issue to me?

**Comment by itsalaidbacklife** [comment]
Resolved by #439
