### ISSUE TITLE
[Bug]: Close buttons have wrong style in TargetingOverlay, RulesDialog, and ScrapDialog

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#446]
### Bug Summary

We frequently use an “X” button in dismissible dialogs and overlays, and several of them have incorrect styles 

### Detailed Description

The ScrapDialog, TargetSelectionOverlay, and RuleaDialog all have the incorrect button styles for this X button. They should look like the X in the MoveChoiceOverlay: no background color and an X icon. Instead they have a white background, and the TargetSelectionOverlay specifically has no icon visible.

To fix it we should revise the close buttons in these components to match the style from the MoveChoiceOverlay

### Current Behavior

They currently look like this
![IMG_4491](https://github.com/cuttle-cards/cuttle/assets/6520704/81d16806-9b9f-417e-b108-8e70ffa5b355)

![IMG_4490](https://github.com/cuttle-cards/cuttle/assets/6520704/57dbbfbd-713c-4f0d-95b4-68b49f13cadb)
![IMG_4489](https://github.com/cuttle-cards/cuttle/assets/6520704/b81c98bb-4fe8-4284-bbf6-4b0caecc8b73)

### Expected Behavior

They should look like this
![IMG_4492](https://github.com/cuttle-cards/cuttle/assets/6520704/3dcd309a-21a5-4c2a-b260-fa14c679392d)

### Steps to Reproduce

1.
2.
3.

**Comment by web-dev-kushal** [comment]
I want to work on this issue. Pls do assign me

**Comment by itsalaidbacklife** [comment]
> I want to work on this issue. Pls do assign me
> 
> 

Have at it! Feel free to ask any questions about the issue here. If you'd like help setting up, you can chat with me and the other devs on our [discord](https://discord.gg/dS5BRjaHrm)

**Comment by Mal402** [comment]
Hey, I think this is something that I can take on!

**Comment by kawaljen** [comment]
Hey can I work on this one ?

**Comment by itsalaidbacklife** [comment]
> Hey can I work on this one ?

Yes please!

**Comment by kawaljen** [comment]
![Screenshot from 2024-01-21 10-33-05](https://github.com/cuttle-cards/cuttle/assets/7325003/9276b0ef-eebf-4b47-a54b-1e35f53dc3de)

**Comment by kawaljen** [comment]
![Screenshot from 2024-01-21 10-35-26](https://github.com/cuttle-cards/cuttle/assets/7325003/2a9dfdfe-59c7-495a-a64f-c2a5399a8214)

**Comment by kawaljen** [comment]
![Screenshot from 2024-01-21 10-36-22](https://github.com/cuttle-cards/cuttle/assets/7325003/ce699f2e-c63a-49e7-b9a2-97d9293d470b)
