### ISSUE TITLE
[Feature]: Direct new users to Signup and returning users to Login pages on initial navigation

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#447]
### Feature Summary

New users need to use the signup page and returning users need the login page. We should use a form of persistent key/value storage to allow the application to identify whether the unauthenticated user has previously authenticated and direct them to the appropriate page accordingly.

### Detailed Description

The persistent storage variable (which could be called something like) `isReturningUser` should be consumed during the `mustBeAuthenticated()` navigation guard in `src/router.js` so that if a user is not authenticated when navigating to a protected page e.g. `HomeView`, they direct to `LoginView` if `isReturningUser` is `true`, and to `SignupView` if it's false.

One question is whether the persistent variable `isReturningUser` should be stored in the `cookie` or in `window.localStorage`. Discussion is welcome on the approach

**Comment by Haviles04** [comment]
I'd like to take this!

**Comment by itsalaidbacklife** [comment]
@Haviles04 have at it!

Update: let's use cookies and set them with `res.cookie()` in the login and signup actions upon successful auth ([docs](https://sailsjs.com/documentation/reference/response-res/res-cookie))
