### ISSUE TITLE
[DevEx]: Apply eslint rule for element-attribute-order to enforce consistent directive/attribute ordering in html

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#459]
### Improvement Summary

The Vue Style guide recommends a specific [order for attributes in html tags](https://v2.vuejs.org/v2/style-guide/?redirect=true#Element-attribute-order-recommended). We've loosely followed this but we could make this explicit and automatic by using the corresponding [eslint rule](https://eslint.vuejs.org/rules/attributes-order.html#vue-attributes-order).

### Detailed Description

This rule applies to html in vue templates to define the order that attributes (including directives) should appear e.g.

```
<!-- ✓ GOOD -->
<button id="someId" v-model="someVar" @click="someFunc" />

<!-- ✗ BAD -->
<button @click="someFunc" v-model="someVar"  id="someId" />
```

We should configure the rule in `.eslintrc.js` so that it causes an error when violated and correspondingly update all the template code that breaks the rule so everything passes without errors.

**Comment by kawaljen** [comment]
Hello, can I work on this one ?

**Comment by itsalaidbacklife** [comment]
> Hello, can I work on this one ?

Yes of course! Please feel free to ask any questions about the issue or how to approach it in this thread. Or if you'd prefer help in real time, you can join our [discord](https://discord.gg/6vQCFa6nvP) and use the #code channel to chat with myself and the other devs

**Comment by kawaljen** [comment]
Hello, 
Doing the ordering is pretty straightforward by changing a .eslintrc.js rule, but it throws warnings and errors. 
Should I try to fix them, do an other issue for that or just run the eslint on local to order the attributes, and then revert the eslintrc.js back before uplaoding ?
thanks!

**Comment by kawaljen** [comment]
16 warnings of 3 kinds ->
- Prop 'username' requires default value to be set
-  v-on event '@resolveThree' must be hyphenated
- Prop "modelValue" should define at least its type
2 errors ->
- Custom elements in iteration require 'v-bind:key' directives
- This 'v-if' should be moved to the wrapper element

**Comment by itsalaidbacklife** [comment]
@kawaljen yes please fix the errors and warnings; thank you! We run the linter in CI before merging code so it's supposed to catch these but it looked like some slipped through.

**Comment by kawaljen** [comment]
Ok will do !

**Comment by kawaljen** [comment]
Hey, I have a question about a warning the changing the lint settings gets, 

on MarkdownContent.vue -> warning  'v-html' directive can lead to XSS attack

That v-html directive is unsafe in the case that the html is injected by user input. 
But in the code, the text is hardcoded in the translation pluggin json and doesn't even use any html tags.. 

The code actuallly uses a pluggin named marked.js to display that text, and that is why it needs that v-html directive. I feel the pluggin is not usefull now.. but am I right ?
I can sanitise the html to get rid of the warning, but from my research, it means that I have to install a pluggin..

What do you think ?

**Comment by itsalaidbacklife** [comment]
> Hey, I have a question about a warning the changing the lint settings gets,
> 
> on MarkdownContent.vue -> warning 'v-html' directive can lead to XSS attack
> 
> That v-html directive is unsafe in the case that the html is injected by user input. But in the code, the text is hardcoded in the translation pluggin json and doesn't even use any html tags..
> 
> The code actuallly uses a pluggin named marked.js to display that text, and that is why it needs that v-html directive. I feel the pluggin is not usefull now.. but am I right ? I can sanitise the html to get rid of the warning, but from my research, it means that I have to install a pluggin..
> 
> What do you think ?

Great question! Generally `v-html` does introduce security vulnerabilities, but in particular it's problematic when used on user generated content (basically if users can input their own content, then you can't trust that it's safe to run). But in contrast this is run on code that's explicitly approved as a part of the PR process, which significantly reduces the risk.

@seriouslysean what do you think? Did you envision sanitizing the input when you added the `v-html` + markdown rendering? Or were you thinking that the PR process should solve that issue?

@kawaljen I think it's okay to leave it without sanitization for now. But great question. It's important to consider security concerns like this, so thanks for asking

**Comment by seriouslysean** [comment]
The only time the markdown component will be used (at this time) is with localized content from the json files, so I don't think it's necessary to sanitize it at all right now since we're all putting eyes on it and manually approving the content.

If we ever plan to expand the usage of the markdown component and use it for user generated content or any third party content then yeah, I'd say go for it. 

Great question and thanks for looping me in @itsalaidbacklife 👍

**Comment by kawaljen** [comment]
Hey again !
I am having difficulties with the tests with cypress

On Cypress.Commands.add('signupPlayer', (player) => {...} 
I get an error on the .then -> Error: Cannot disconnect- socket is already disconnected

That can be fixed by adding wait ->

Cypress.Commands.add('signupPlayer', (player) => {
  cy.wait(500);
  cy.window()
    .its('cuttle.app.config.globalProperties.$store')
    .then((store) => store.dispatch('requestSignup', { username: player.username, password: player.password }));
  cy.log(`Signed up player ${player.username}`);
});

Or on sail.js
    io.socket.on('connect', () => {
      io.socket.disconnect();
      io.socket.reconnect();
    });

But that are territories that I am not familiar with !

**Comment by kawaljen** [comment]
Hey again !
I am having an error testing with cypress

On Cypress.Commands.add('signupPlayer', (player) => {...}
I get an error on the .then -> Error: Cannot disconnect- socket is already disconnected

That can be fixed by adding a wait ->

Cypress.Commands.add('signupPlayer', (player) => {
cy.wait(500);
cy.window()
.its('cuttle.app.config.globalProperties.$store')
.then((store) => store.dispatch('requestSignup', { username: player.username, password: player.password }));
cy.log(Signed up player ${player.username});
});

what do you think ?

**Comment by seriouslysean** [comment]
I'm a little confused why you'd need an await for moving TV e order of attributes around as it doesn't really change anything else about the code.

We have a persistent session but that does cause intermittent test failures and I wonder if that's what you're seeing.

Do you see the error every time, or is it also intermittent in your PR?

**Comment by itsalaidbacklife** [comment]
@kawaljen are you on a windows machine? Does the error say "that user already exists"? This sounds like #521 which is a known problem  that only appears on windows systems. If you're running one test at a time you could solve it by rebooting the backend between tests, or more comprehensively you could setup windows subsystem Linux to fix it entirely. We have a section in the setup docs about it. 

We want to avoid adding arbitrary waits to the tests as they slow things down, but it's a nuisance of a bug that I'd love to fix globally.

**Comment by kawaljen** [comment]
@seriouslysean 
that error occurs with the code straight from the repo, without any changes from me

**Comment by itsalaidbacklife** [comment]
> @seriouslysean that error occurs with the code straight from the repo, without any changes from me

@kawaljen does your issue look like #521? If you're on a Windows machine and seeing errors in tests that 'That username is already registered to another user; try logging in!', then you are likely encountering a known issue that appears on windows systems. We're working to address it, but in the mean time, the easiest way around it for you will be to set up Windows Subsystem Linux which lets you run the app in a unix-based environment where this problem does not currently appear. 

We have notes on this in the [setup docs](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#windows-11)

**Comment by kawaljen** [comment]
Yes, I am on windows system !
I didn't have the "that user already exists" error message, but it was failing as the test does the signup for the second time.. It does look alike
(I was following the contributing docs, it wasn't mentioned ;) )

Anyway the code passed the tests, i am on the last step
