### ISSUE TITLE
[Bug]: ScrapDialog has old dialog style (doesn't use `BaseDialog`)

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#473]
### Bug Summary

All the in game dialogs at this point are supposed to consume the BaseDialog component to give them a consistent style. The ScrapDialog fails to do this, and looks out of place as a result.

### Detailed Description

Generally our dialogs rendered with `BaseDialog` have a consistent style that has our chocolate and cream theme colors like so:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/acfb76d5-1c33-4b56-9ba6-00d2aa143e35)

But the ScrapDialog (for viewing the scrap) currently does _not_ use the BaseDialog and so it is white and black:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/306415bd-0bb8-481b-8342-dacc9a5bacb3)

We should update the ScrapDialog.vue component so that it instantiates a `basedialog` instead of the raw `v-dialog` in order to apply the appropriate styles

### Steps to Reproduce

1.
2.
3.

**Comment by haaarsh619** [comment]
Hello there ! I'm a first-timer on open source and I would love to participate.  can I give it a shot ?

**Comment by itsalaidbacklife** [comment]
@haaarsh619 Yes of course! If you have any questions about how to approach the issue, feel free to ask them in this thread. Or if you'd prefer help in real-time, you can join our [discord](https://discord.gg/6vQCFa6nvP) and use the #code channel to chat with me and the other devs

**Comment by itsalaidbacklife** [comment]
Resolved by #496
