### ISSUE TITLE
[Bug]: Nav drawer doesn't highlight the stats page link when viewing stats

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#476]
### Bug Summary

Because the stats page redirects to the url for a specific season, the 'stats' link in the nav drawer doesn't show the link which doesn't match the page url and the link doesn't get highlighted.

### Detailed Description

This is how the stats page looks. Notice that there is no highlight in the nav drawer on the Stats link even though you are viewing that page.

![image](https://github.com/cuttle-cards/cuttle/assets/6520704/f5a67aac-08fa-42ba-96b8-5cd5f775fda9)

In comparison, when you go to 'Play' the link is highlighted:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/3e5819b1-a54b-41c7-8930-06e3d95b0979)

Check out the vuetify [docs](https://vuetifyjs.com/en/api/v-list-item/#props-exact) on the `exact` prop for `v-list-item` to see if we can leverage this to allow it to match on the /stats route even when the path is /stats/7 for a specific season

### Steps to Reproduce

1.
2.
3.

**Comment by Haviles04** [comment]
This can be closed, fixed by #530
