### ISSUE TITLE
[Feature]: Add loading state (skeleton loader) to Stats Leaderboard

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#484]
### Feature Summary

The StatsLeaderboard currently has a `loading` prop that is given a value but never used. We should conditionally render a skeleton loader when this prop is true (and the table when it is false) to clarify that the data is loading.

### Detailed Description

See the Vuetify docs on [skeleton loaders](https://vuetifyjs.com/en/components/skeleton-loaders/) for details on how to implement them. Essentially the `StatsLeaderboard` component should use `v-if` to conditionally render a skeleton loader that looks like the leaderboard table when the `loading` prop is true, and use `v-else` to show the data table when the data has finished loading.

This is what the table currently looks like
<img width="1437" alt="image" src="https://github.com/cuttle-cards/cuttle/assets/6520704/816845c3-b130-4ee6-9031-3fa11984f0e0">

This is what it looks like while the data is loading
<img width="1256" alt="image" src="https://github.com/cuttle-cards/cuttle/assets/6520704/81bafbbb-d174-4f9a-9a28-a0b46b1864f2">

Instead of this blank screen, we should show a skeleton loader on the leaderboard section, and additionaly put the `v-select` in the `StatsView` page (used to select a season) into a loading state by setting its `loading` prop to the existing `dataIsLoading` variable

**Comment by SamMrach** [comment]
@itsalaidbacklife can you please assign it to me ?

**Comment by itsalaidbacklife** [comment]
@SamMrach Currently @haaarsh619 is working on this and it's almost done, so how about picking up a different frontend issue like https://github.com/cuttle-cards/cuttle/issues/498?

If you'd like to discuss the issue, general setup, or help finding one that aligns with your skills and/or interests, you can join us on [discord](https://discord.gg/6vQCFa6nvP) and use the #code channel to chat with myself and other devs in realtime
