### ISSUE TITLE
[Feature]: Add landing page video + background image to login page and auto-scroll to the login form when mounting `LoginView` in the Login mode.

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#485]
### Feature Summary

Currently the Signup and Login pages are very similar except the signup page has an additional screen-height worth of content at the top to showcase the board background and an introductory video. The difference between the pages can be jarring when navigating between signup and login. To remedy this we should make them have the same content and use programatic scrolling to achieve the effect of directing returning users immediately into the login form.

### Detailed Description

Signup and Login are both handled by the `LoginView` page, which conditionally renders this top section only when users are signing in, under the assumption that returning users do not wish to see introductory content every time:
<img width="1440" alt="image" src="https://github.com/cuttle-cards/cuttle/assets/6520704/e6373764-1096-4a0a-b66a-3ae9004a73ea">

However this causes jumpy, inconsistent navigation when switching between signup and login:

https://github.com/cuttle-cards/cuttle/assets/6520704/3bc20290-072d-4b34-b9a7-e7107e5097d4

In order to make the navigation smoother and the layout more consistent between these versions of the same page, we should remove the conditional rendering of the top section so that this page  _always_ displays the top introductory section (with the game board and video) above the form for signup/login.

In order to enable returning users to directly log in without needing to manually scroll past this introductory section, we should then make it so that the LoginView page programatically scrolls to the login form when the component mounts when you are visiting `/#/login` but not when you are visiting `/#/signup`. This way new users still see the intro content front and center, and returning users can easily ignore it, but the page layout will be more consistent between signup and login, making navigation between them smoother and more intuitive.

**Comment by Haviles04** [comment]
Got this one
