### ISSUE TITLE
[Feature]: Apply the chocolate and cream colors to the `SpectatorListMenu` in-game

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#497]
### Feature Summary

The in-game spectator menu (`SpectatorListMenu`) has a style that is inconsistent with the rest of the app. We should update it to use the branded colors

### Detailed Description

This is the style that the correctly branded `GameMenu.vue` component has (note the background and text colors)
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/ad03613f-036c-489c-922c-e54c99b91e12)

But the `SpectatorListMenu` is plain black and white:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/0112c2f6-02ac-469d-bd99-74161a54691a)

We should update the `SpectatorListMenu` to match by using the `surface-2` (cream) color for its background and the `surface-1` (chocolate) color for its text

**Comment by Haviles04** [comment]
I'll take this
