### ISSUE TITLE
[Bug]: Spectate endpoint server 500 response

### ISSUE THREAD

**Issue by Haviles04** [cuttle-cards/cuttle#503]
### Bug Summary

The spectate endpoint currently throws a 500 server error while running test in home.spec.js, this should be changed to a  400 error.

### Detailed Description

Currently if you run test in `home.spec.js` the test starting on line 215  `it('Does not show open or completed games in spectate tab', () => {}` will pass, but your server console will log a 500 error 
```
error: Sending 500 ("Server Error") response:
 TypeError: Cannot read properties of undefined (reading 'id')
    at Object.populateGame (cuttle/api/services/gameService.js:10054)
    at async Promise.all (index 0)
    at async module.exports [as game/spectate] 
```
This is happening after we force disconnect the socket and try to rejoin the game. We should handle this case and throw a `res.badRequest()` resulting in a 400s error code.

### Current Behavior

Error: 500 server error

### Expected Behavior

400 error

### Steps to Reproduce

1.
2.
3.

**Comment by arnaut08** [comment]
![image](https://github.com/cuttle-cards/cuttle/assets/52157140/361d1f0d-c1c6-4915-8d9b-c6883b6667b8)

I noticed this today while trying to test my changes. Please correct me if I'm wrong, but from what I can tell is that we already have a condition to handle this and apparently the players property of game is an empty array in such case and not any false-y value. We can probably fix the condition to check for array length instead.

**Comment by Haviles04** [comment]
> 
> ![image](https://github.com/cuttle-cards/cuttle/assets/52157140/361d1f0d-c1c6-4915-8d9b-c6883b6667b8)
> 
> I noticed this today while trying to test my changes. Please correct me if I'm wrong, but from what I can tell is that we already have a condition to handle this and apparently the players property of game is an empty array in such case and not any false-y value. We can probably fix the condition to check for array length instead.
> 

This check happens after we fetched a game, given the Id was provided, this issue should address the API not receiving an ID, which would happen at the start of the file.

**Comment by arnaut08** [comment]
I tried to add logs to debug this further. The gameId is there in this test case and that's how the game data is also being fetched successfully right before the condition which I mentioned earlier.
Also, I can see that we already have a check for gameId in the beginning of this method. 
![image](https://github.com/cuttle-cards/cuttle/assets/52157140/6a40d252-ae78-4f3f-86a1-2f31e202ac6c)

**Comment by Haviles04** [comment]
> I tried to add logs to debug this further. The gameId is there in this test case and that's how the game data is also being fetched successfully right before the condition which I mentioned earlier.
> Also, I can see that we already have a check for gameId in the beginning of this method. 
> ![image](https://github.com/cuttle-cards/cuttle/assets/52157140/6a40d252-ae78-4f3f-86a1-2f31e202ac6c)
> 

You are right, the endpoint is receiving a game that is already over.So we should make a check to see if the game is over and if it is we should throw a 400 error instead letting it 500

**Comment by fuveluck** [comment]
Then I start with this issue after consultation in discord :)
