### ISSUE TITLE
[Feature]: Update colors in `StatsScoringDialog.vue` to leverage themes' chocolate and cream colors

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#511]
### Feature Summary

The `StatsScoringDialog` is used to explain how the ranking system works. It has a section showcasing the point chips that players earn based on their weekly ranked performance that uses a white background. This would look more consistent with the overall look and feel if the background were made cream and the text color were chocolate.

### Detailed Description

Specifically it's this section of the `StatsScoringDialog`:

![image](https://github.com/cuttle-cards/cuttle/assets/6520704/f545bde4-534c-4076-91fd-a40527288331)

Currently the background is white and the text is black. It would look better if this was a cream background (surface-2) and the text were chocolate (surface-1). 

Additionally we should set `:persistent="false"` on the `StatsScoringDialog`'s instance of the `BaseDialog` so that it closes when you click outside the dialog, given that this is an informational dialog that doesn't require you to make a decision.

**Comment by karan3267** [comment]
Hi, Can i take this up?

**Comment by itsalaidbacklife** [comment]
@karan3267 yes of course; have at it!
