### ISSUE TITLE
[Feature]: Add skeleton loader to HomeView (Play) page game list

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#512]
### Feature Summary

When a user navigates to the HomeView (where we display the list of games available to play), we request the list from the server. We should display

### Detailed Description

We can define a `loading` state in the `HomeView`'s `data()`, default it to `false`, then set it to `true` in the `created()` hook before making the api call, then set it to `false` after the api call resolves. We could then render a `<v-skeleton-loader>` inside the list of games to show placeholders for the games that are being requested.

See the `StatsView` for an example of using a skeleton loader in Cuttle and the [vuetify docs](https://vuetifyjs.com/en/components/skeleton-loaders/) for full documentation on this component

**Comment by kawaljen** [comment]
Hello could I work on this one ?

**Comment by itsalaidbacklife** [comment]
Yes, of course! Have at it @kawaljen
