### ISSUE TITLE
[DevEx]: Refactor `BaseSnackbar`'s `color` prop to have default value of `'error'`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#513]
### Improvement Summary

The `BaseSnackbar` component is used to configure and style snackbars to have a consistent look and feel. It accepts a `color` prop to configure the snackbar's background color, but all of the current consumers of `BaseSnackbar` use the same `color="error"`. It would be more DRY to keep the prop but give it a default value of `'error'` so all consumers could omit the prop.

### Detailed Description

This way all the consumers of `BaseSnackbar`, namely `ReuathenticateDialog`, `GameView`, `HomeView`, and `LoginView` can remove the `color` prop form `BaseSnackbar`, but if we encounter a usecase for a non-error snackbar, we can configure the color by overriding the `color`

**Comment by swebe3qn** [comment]
Hi, I'd like to work on this issue? Is it possible to assign it to me? :-)
