### ISSUE TITLE
[DevEx]: Update Node to latest stable version

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#516]
### Improvement Summary

At this point the node version specified in `.nvmrc` and the `package.json` `engines` section is several minor versions behind. We should update node to the latest stable version, fixing any emergent bugs that appear when we do so.

### Detailed Description

To do this, we should confirm the latest stable version (LTS) of node on [their official site](https://nodejs.org/en) (at the time of writing this issue, LTS is 18.17.1), then update `.nvmrc`, `package.json`, `package-lock.json`, `.Dockerfile` and `.npm-run-script.yml` (and any other relevant files) to replace all instances of `18.12.1` (the currently specified node version) with the latest stable version at that time.

**Comment by seriouslysean** [comment]
@jerryh-jr is going to pick this up.

**Comment by jerryh-jr** [comment]
@itsalaidbacklife and @seriouslysean looking into this.
