### ISSUE TITLE
[Bug]: CreateGameDialog has two separate forms inside it

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#518]
### Bug Summary

Currently the `CreateGameDialog` instantiates a `<form>` element that wraps the switch for controlling ranked, and a separate `<v-form>` element that wraps the text field for the game name. Instead, the `<v-form>` should wrap both the ranked-play switch and the game-name text field. 

### Detailed Description

The `<form>` tag that is used to wrap the switch also includes the `<stats-scoring-dialog>` in order to make them appear on the same line. We should replace this with a regular `<div>` that puts the switch + stats scoring dialog on one line, and move the `<v-form>` wrapper to include the entire contents of the dialog #body

### Steps to Reproduce

1.
2.
3.

**Comment by omriattiya** [comment]
hi , can you assign this to me?
