### ISSUE TITLE
[Bug]: StatsUsageChart title is not reactive

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#523]
### Bug Summary

The StatsUsageChart displayed on the StatsView page shows a chart with metrics for the number of games played and the number of unique players each week, with a title like”Cuttle played in Diamonds 2022”, where “Diamonds 2022” is the name of the selected Season being viewed. The chart data correctly updates when the user selects a new season at the top of the page, but the chart name remains out of date, showing the old chart title with the previously selected season.

### Detailed Description

This is likely a reactivity issue that has to do with how the StatsView, StatsUsageChart, and BaseLineChart pass data as props. We should try updating the chart id as well as its title so the canvas id includes the season id and then update the test in the stats.spec.js that checks that the chart appears to also confirm that it has the correct id (as a proxy for the title, which we likely can’t assert because it lives in the canvas element)

### Current Behavior

The chart title stays the same when selecting a new season even though the chart data correctly updates

### Expected Behavior

The chart title updates to reflect the newly selected season

### Steps to Reproduce

1. Go to https://cuttle.cards/#/stats
2. Look at the chart underneath “Site Usage”, note the general shape of the data and the chart title e.g. “Amount of Cuttle played in Hearts 2023”
3. At the top of the page select a different season e.g. Diamonds 2023.
4. Note how the chart data changes but the chart title does not

**Comment by jerryh-jr** [comment]
@itsalaidbacklife I would like to work on this.

**Comment by LurieK** [comment]
I would also like to help if help is still needed.
