### ISSUE TITLE
[Feature]: Update StatsUsageChart to allow selecting whether to show Games Played, Unique Players, or both.

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#524]
### Feature Summary

The StatsView page shows a chart of how many games of Cuttle are played by how many different players each week for the selected season. Because there are more games played than players, the Y-axes scale is tailored to show the number of games, making it difficult to tell how many players there are without hovering over a specific data point. We should add a v-select that allows users to choose to view Games Played, Unique Players, or Games Played and Unique Players, which should be the default

### Detailed Description

See how the y-axis scale makes it easy to tell the number of games but hard to tell how many players there are.
![IMG_4653](https://github.com/cuttle-cards/cuttle/assets/6520704/ba1512bc-36a0-4d9f-9760-b9aa2ba04823)

We should still default to showing both of these, but allow users to select seeing just one or the other to redraw the chart with a new scale that is tailored to the specific metric being analyzed.

To implement this, we should update `StatsUsageChart.vue` so that it has a v-select above the chart that sets a variable that’s used to update the computed data sets sent to the `BaseLineChart` by removing one or the other dataset if the user selects just one metric.

**Comment by haaarsh619** [comment]
## as we are using chartjs this can be done via clicking on legends.

https://github.com/cuttle-cards/cuttle/assets/72140070/e249cd77-33b5-4f8d-a87f-6f9729c818eb

**Comment by itsalaidbacklife** [comment]
Woo! That's great! We may want to consider adding an affordance to clarify that this is how it works, but given the current functionality, I'm calling this done. Thanks @haaarsh619 great find
