### ISSUE TITLE
[DevEx]: Replace Vuex with Pinia

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#537]
### Improvement Summary

Cuttle uses Vuex for state management. Now that the app has been updated to use Vue 3, we can replace Vuex with its officially supported replacement: pinia.

### Detailed Description

[Pinia](https://pinia.vuejs.org/introduction.html) is the official state management library for the Vue ecosystem. It is essentially an upgrade to its predecessor, Vuex, which Cuttle still uses. The central value proposition for switching to pinia is a simpler and more type-safe api for calling methods on the stores as while vuex relies on calling `.dispatch()` and `.commit()` and passing function names as strings, pinia allows store consumers to directly call methods on the store instance.

Upgrading will essentially require updating all of the vuex modules in `src/store/modules` to be pinia stores and updating the component references to those stores to replace the `.dispatch()` and `.commit()` calls with regular method calls on their respective functions e.g. `this.$store.dispatch(‘requestLogin’)` will become `this.authStore.requestLogin()`. Additionally, most of the store mutations will no longer be necessary, as store consumers can directly mutate variable state in the store without a mutation function. The only mutations worth keeping will be the complex ones that update data in a nuanced way, like the `game` store’s `updateGame()` mutation or the `gameList` store’s `gameStarted()` mutation. See the [pinia migration guide](https://pinia.vuejs.org/cookbook/migration-vuex.html) for additional guidance.

For the initial implementation, we will stick with the Vue options API that the components already use to minimize the scope of this change. See the [pinia docs on options api usage](https://pinia.vuejs.org/cookbook/options-api.html) for details and examples.

**Comment by Haviles04** [comment]
I'll take this
