### ISSUE TITLE
[Feature]: Add aria attributes to all the icons 

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#542]
### Feature Summary

Cuttle uses icons semantically, meaning all the icons have an intended meaning. For accessibility purposes, these icons should therefore have certain metadata set. We should update the existing uses of icons to set this data accodingly.

### Detailed Description

Specifically, each `<v-icon>` in the application should set:
1. `aria-label="descriptive text based on what the icon is for"`
2. `aria-hidden="false"` (this ensures it is read on screen readers)
3. `role="img"` 

We should set these for every icon in the application, which you can find by doing a search for all instances of `<v-icon`

**Comment by dushyantpant5** [comment]
@itsalaidbacklife , Can i do it?
