### ISSUE TITLE
[Feature]: Update VS AI experience to use the background image

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#543]
### Feature Summary

In order to make the VS AI experience match the PVP Cuttle experience, we should update the GameView to use the same background image that the PVP application does: https://github.com/cuttle-cards/cuttle/blob/main/public/img/game/board-background.svg

### Detailed Description

This is a copy of a [corresponding issue](https://github.com/Human-AI-Interaction/cuttle-bot/issues/2) in the [VS AI application](https://github.com/Human-AI-Interaction/cuttle-bot), just to track it as a TODO from the main repo. 

We should apply the same image and css that the `GameView` uses in this repo to the CuttleBot repo so that players can enjoy a similar look and feel by seeing the same game board background.

**Comment by JonasThers** [comment]
Working on this https://github.com/Human-AI-Interaction/cuttle-bot/pull/5
