### ISSUE TITLE
[Feature]: Replace cards in vs AI experience with the ones used in PVP

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#547]
### Feature Summary

We should update the CuttleBot repo to use the same deck of cards that the PVP experience uses.

### Detailed Description

This is a placeholder issue that's meant to make it easier to find the [corresponding issue](https://github.com/Human-AI-Interaction/cuttle-bot/issues/3) from the [CuttleBot repo](https://github.com/Human-AI-Interaction/cuttle-bot) which is a separate project from the main PVP app.

This is the current look of CuttleBot:
<img width="1440" alt="image" src="https://github.com/Human-AI-Interaction/cuttle-bot/assets/6520704/f49fcecc-7d21-46aa-b398-cd032336e560">

Compared with PVP:
![image](https://github.com/Human-AI-Interaction/cuttle-bot/assets/6520704/261ca103-4fa6-4b13-be63-156a0580d48a)

We should replace the cards (fronts e.g. the ace of clubs and the cardback used for the deck and opponent's hand) with the cards that are used in the pvp experience. This will significantly improve the look and feel while making the vs AI experience more consistent with the rest of the app.

**Comment by theavitw** [comment]
I Can Work o this issue.

**Comment by itsalaidbacklife** [comment]
Resolved by https://github.com/Human-AI-Interaction/cuttle-bot/pull/12
