### ISSUE TITLE
[Feature]: Add 4px margin between icons and tab labels in `TheHeader`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#560]
### Feature Summary

`TheHeader` component has tabs that appear in the upper right, with icons and labels for each page e.g. 'Play'. The icons are too close to the text and would look better with a 4px margin between them. 

### Detailed Description

See the image below.
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/62b880c8-d662-47ab-9d2d-ae7796cfd3b2)

We should add 4px of margin between the icons and the text in the tabs inside `src/components/TheHeader.vue` so the elements have room to breathe.

**Comment by DilushaHesaranga** [comment]
### Hey there !!!

_Do you still meed help with this issue : )_
**If yes, leave a comment** 

> I am glad to work with this issue.

**Comment by itsalaidbacklife** [comment]
@DilushaHesaranga have it it! Feel free to ask any questions you have about the issue here, or if you'd prefer real-time support you can join us on [discord](https://discord.gg/zZujC7Tp5j) where you can chat with myself and the other devs

**Comment by DilushaHesaranga** [comment]
Sure

> @DilushaHesaranga have it it! Feel free to ask any questions you have about the issue here, or if you'd prefer real-time support you can join us on [discord](https://discord.gg/zZujC7Tp5j) where you can chat with myself and the other devs

**Sure!! I will fix them and reach you soon : )**
