### ISSUE TITLE
[Bug]: Discord Button Not Responsive  In login Page

### ISSUE THREAD

**Issue by haaarsh619** [cuttle-cards/cuttle#572]
### Bug Summary

Discord button is not responsive on mobile

### Detailed Description

The discord button in LoginView.vue is not responsive on mobile  the text and icon overflow.
it occurs when French or Spanish Language is Selected. This Issue occurs when language is Changed.

![image](https://github.com/cuttle-cards/cuttle/assets/72140070/3c0c2c16-4045-42b6-8fdc-b1588e485ff4)

### Steps to Reproduce

1. After Login Change the language from Menu  
2. Then Logout 
3. Then Scroll to the Login section there  is discord button text and icon in login section.

**Comment by dushyantpant5** [comment]
@haaarsh619 , can I try it?

**Comment by haaarsh619** [comment]
> @haaarsh619 , can I try it?

Yes sure, 
If you have doubts  or need any help you can also use the #code channel of our [discord](https://discord.gg/6vQCFa6nvP) .

**Comment by dushyantpant5** [comment]
<img width="1147" alt="Screenshot 2023-09-23 at 9 38 45 PM" src="https://github.com/cuttle-cards/cuttle/assets/60127798/206e429a-1305-4c34-83ee-2a1c827fd1c1">

I fixed it with adding <span> and doing inline styling. Is there any style class in Vue to do it? Or this I commit it in this way only?

**Comment by haaarsh619** [comment]
I am not sure can you commit and then @itsalaidbacklife will review it.

**Comment by Shahidkhatrii** [comment]
Hi @haaarsh619 I would like to fix it if this issue is still open

**Comment by itsalaidbacklife** [comment]
Hi @Shahidkhatrii there is an open PR #577 that addresses this. That will likely be merged soon so it would be better to pick up another issue. If you're interested in frontend try filtering for issues that are labeled with "frontend" and "good first issue". If you'd like to chat with myself or other devs about finding a suitable one, you can reach out on the #code channel of the Cuttle [discord](https://discord.gg/arWabYp8SC)
