### ISSUE TITLE
[Feature]: Convert page routing to use history mode

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#580]
### Feature Summary

We should update the routing strategy to use vue's history mode

### Detailed Description

Currently the Cuttle vue SPA uses the [hash mode](https://router.vuejs.org/guide/essentials/history-mode.html#Hash-Mode) which separates all the individual pages with a # e.g. https://cuttle.cards/#/login. This has negative SEO impact because web crawlers do not correctly index pages using #.

To address this, we should update the router configuration to [utilize history mode](https://router.vuejs.org/guide/essentials/history-mode.html#Hash-Mode), which would change the routes to https://cuttle.cards/login etc. This will require updating tests that refer to routes using #/, so that they correctly look for the #. 

Additionally, per the Vue router docs for history mode, we will need to update the server `config/routes.js` file in order to define a catch-all route that directs all unrecognized urls to `index.html` so that vue can handle them. That way if a user navigates directly in their browser to https://cuttle.cards/about they will load the vue app and vue can render the about (rules) page. Without this, the server will not recognize the https://cuttle.cards/about url and direct navigation to pages of the app will 404.

**Comment by itsalaidbacklife** [comment]
@premtw excellent! This would be a fabulous contribution. Feel free to ask any questions about the issue here. If you have questions about setup or would like real time support, you can use the #code channel of the [discord](https://discord.gg/3AjsjQByha) to chat with myself and the other devs

**Comment by premtw** [comment]
Thanks @itsalaidbacklife Will raise a PR once it is completed

**Comment by premtw** [comment]
@itsalaidbacklife Could you please add the hacktoberfest tag to this MR?

**Comment by itsalaidbacklife** [comment]
@premtw I added the hackatoberfest label to the issue, though FYI in general it shouldn't matter because the hacktoberfest topic is applied to the entire repo so any PR's merged into main will count even without the label
