### ISSUE TITLE
[Bug]: App navigation disappears between 960px and 1280px

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#581]
### Bug Summary

Devices between 960px and 1280px wide currently lose the nav links in `TheHeader` (top nav) but do not trigger opening `TheFooter`, leaving them unable to navigate between pages 

### Detailed Description

See screenshot:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/9e035b4e-607f-4ca3-8227-1ee474a115d7)

Notice there are no nav links in the upper right corner as seen on larger devices (> 1280px wide):
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/3fe6ad4c-e27d-4c4e-a69a-a4e4aa0d2958)

And neither does TheFooter appear with nav links in the bottom of the page, as seen on smaller devices:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/e6185f27-ecea-4722-a325-2c9e0ebdafe9)

This is a problem because in `App.vue`, `TheFooter` is rendered conditionally based on the vuetify breakpoint `smAndDown` i.e. below 960px. In contrast, `TheHeader` conditionally renders the nav links in the `<v-toolbar-items>` based on vuetify's `mobile` breakpoint, which triggers below 1280px, leaving a gap between the two for devices between 960px and 1280px wide.

To solve this, we should make the use of breakpoints match. Since the `mobile` breakpoint is more inclusive than was previously anticipated, the best way to sync these is by updating `TheHeader.vue` so that it renders the toolbar based on the `smAndDown` breakpoint the same way that `App.vue` uses for `TheFooter.vue` (rather than its current use of `mobile`

### Current Behavior

Devices between 960px and 1280px wide have no navigational elements on the home, stats, and about pages.

### Expected Behavior

Nav links appear in TheHeader for devices > 960px and instead uses TheFooter for navigation for devices smaller than 960px

### Steps to Reproduce

1. Set your browser width to 1000px
2. open the homepage
3. notice there are no links in the header and the footer doesn't appear

**Comment by Srigopalsarda** [comment]
Hi ! Can I please work on this issue?

**Comment by itsalaidbacklife** [comment]
@Srigopalsarda have at it! If you have any questions about the issue feel free to ask them here. If you'd like help setting up or to discuss the issue in real time, you can use the #code channel of our [discord](https://discord.gg/sthNtWaHpe) to chat with myself and the other devs. Happy hacking!

**Comment by Rafajrg21** [comment]
I found the bug while doing my first PR so I searched and saw that this issue existed. It was inactive for 2 weeks and it was a quick fix so I uploaded the fix.
