### ISSUE TITLE
[Feature]: Set color of of nav elements in `TheFooter.vue` to `'newPrimary'`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#583]
### Feature Summary

The navigation elements in `TheHeader` use `newPrimary` (pink) for the active element, but `TheFooter` does not, making it inconsistent. We should make `The

### Detailed Description

See images. `TheFooter.vue` navigation (used on small devices) does not color the selected element:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/8e203c77-49a0-4068-8d50-b05053fe037f)

But `TheHeader.vue` does:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/08fa861e-4e48-4671-8805-0212c7b4cd6d)

We should use the technique to set the color of the active link in `TheFooter.vue` to `'newPrimary'` which is the pink seen in `TheHeader`

**Comment by aybeedee** [comment]
Would like to make this change, can I kindly be assigned

**Comment by itsalaidbacklife** [comment]
@aybeedee have at it! We can only 'officially' assign issues to organization members; generally they are first come, first serve. You're the first to ask, so by all means take dibs :)

Please feel free to ask any questions about the issue in the comments here, or in your PR when you submit one. If you have any questions about general setup, or would like to get help in real time, you can use the #code channel of our [discord](https://discord.gg/6vQCFa6nvP) to chat with me and other devs working on the project.
