### ISSUE TITLE
[Feature]: Add 4px margin between buttons in `CreateGameDialog`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#614]
### Feature Summary

The two buttons in the `CreateGameDialog` are too close together. We should add margin between them

### Detailed Description

The `CreateGameDialog` used in the `HomeView` has a button to cancel and a button to create the game/submit the form. They should be put at least 4px apart. To do this we should use the existing [vuetify spacing classes](https://vuetifyjs.com/en/styles/spacing/) to apply margin right to the cancel button with `class="mr-1"`. 

It would be good to try out 8px with `class="mr-2"` for comparison and pick whichever looks better.

See the current dialog to notice how the buttons touch:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/c6d45b07-4fd4-46af-aa49-03847c748d91)

**Comment by AlisanCavus** [comment]
If its assigned, I can work on it.

**Comment by itsalaidbacklife** [comment]
> If its assigned, I can work on it.

@AlisanCavus we can only "officially" assign issues to members of the the cuttle-cards GitHub org, but you're welcome to take this one if you'd like to work on it

**Comment by anujbarochia** [comment]
In exactly which file change is needed to be made ?

**Comment by itsalaidbacklife** [comment]
> In exactly which file change is needed to be made ?

src/components/CreateGameDialog.vue
