### ISSUE TITLE
[Feature]: Animate transition of resolving a three (revealed card moving into player hand)

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#618]
### Feature Summary

You cannot currently see which card an opponent selected when they pick a card from the scrap with a 3. We should use an animated transition to clarify this interaction

### Detailed Description

Currently, when a player selects a card from the scrap with a 3 you can't see which card was selected, and the resolution looks similar to drawing a card:

https://github.com/cuttle-cards/cuttle/assets/6520704/edab2336-96ab-4f19-bc7a-4f6f88adf9e2

We should clarify this interaction by revealing the selected card on top of the scrap pile and transitioning it towards the hand of the player that played the three. To do this we should update the socket event sent via `Game.publish()` in `api/controllers/game/resolve-three.js` so that it includes the card being moved like

```
      Game.publish([fullGame.id], {
        change: 'resolveThree',
        game: fullGame,
        victory,
        chosenCardId: req.body.cardId
      });
```

That way the frontend can know which specific card to animate in the scrap. Then we should add data to the GameStore for `cardSelectedFromScrap` which we could use to render and animate the selected card. We should then define a new `processResolveThree` function in the `gameStore.js` store which behaves similarly to `processScuttle` by setting the new `cardSelectedFromScrap` value to the card that was just picked, then setting a timeout and after the delay, unsetting `cardSelectedFromScrap` and updating the rest of the game object so that card triggers its leave animation and disappears.

Then we should update the DOM in `GameView.vue` so that the Scrap area can temporarily display the `cardSelectedFromScrap` as a `<GameCard>`  and animate it up-and-right or down-and-right at a diagonal using new transition classes similar to the ones used on the hands, points etc. The card should have it's leave transition to be up-and-right if moving into the opponent hand and down-and-right if moving into the player hand. 

This way we will have a much smoother, clearer interaction that makes it easy to tell which card was selected when your opponent plays a 3.

**Comment by Haviles04** [comment]
Got this
