### ISSUE TITLE
[Feature]: Animate transition of opponent discarding from 4 be revealing the selected cards

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#619]
### Feature Summary

We should animate the transition of when an opponent discards from a 4 by revealing the discarded cards before they move downwards towards the scrap

### Detailed Description

This is a similar issue to #227 and #618 which clarify interactions via animating and revealing cards. 

Currently when you play a 4 and your opponent discards cards, you can see the _that_ the opponent discards (you see two cards move down from their hand) but not _which_ cards the opponent discards. You can only tell by looking at the scrap (or if you have glasses on the field).

Uploading Opponent discarding from 4.mov…

We should clarify this interaction by revealing the cards that the opponent selected for discard before transitioning them downward in the current manner. The cards should be revealed using a flip animation that flips them from card back to card front and then the revealed cards should be moved downward towards the scrap.

To accomplish this, we should update `controllers/api/game/resolve-four.js` so that the socket event sent with `Game.publish()` includes the ids of the cards selected for discard. This could be done as follows:
```
      Game.publish([fullGame.id], {
        change: 'resolveFour',
        game: fullGame,
        victory,
        discardedCardIds: cardsToScrap,
      });
```

From there, the frontend `gameStore.js` should be updated with a new piece of state that tracks the cards being discarded e.g. `discardedCards` which should be filled with the two cards being discarded by your opponent and then cleared out when we update the rest of the game.

Then we should add a new function `processOpponentDiscard()` which sets the `discardedCards` array and then sets a timeout and updates the rest of the game and clears out the `discardedCards`.

We should then update the `<GameCard>` component to enable a flipping transition from card back to card front, and update the `<GameView>` page so that the cards in the opponent hand are flipped and revealed when they are present in the `discardedCards` array. 

The full effect of this should be that when an opponent discards we flip and reveal the discarded cards in their hand before they animate downwards towards the scrap.

Notably, there are a few edge cases to consider:
1. The cards to not need to be flipped when the player has glasses
2. No cards need to be flipped when it is the current player discarding (only their opponent)
3. It is possible that only one card is discarded in which case only that card should be flipped.

**Comment by Haviles04** [comment]
I'll take this one 🚥
