### ISSUE TITLE
[Feature]: Enable language selection from SignupView

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#622]
### Feature Summary

Now that it is possible to to select your preferred language, we should enable users to select a language before logging in. 

### Detailed Description

Currently users can select their preferred language from the `UserMenu` in `TheHeader` after they've logged in:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/bf8459e8-9586-471a-afe8-338d65ff103f)

But new users who have not yet created an account can't select their language of choice until after signing up. We should improve this by adding an element to the top of the signup page for selecting your preferred language:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/8df742f3-04b1-4e6f-8010-b0a3e3655da2)

This could open the same language selection menu that's currently in use in `TheUserMenu`:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/177597e0-e39d-4e0c-b813-584030b775f2)

To do this, we should refactor the language selection functionality into a new `TheLangSelectMenu` component that is consumed by both `TheUserMenu` (as it currently works) and now newly applied to the top of the page directly in `SignupView`.

The result of this would be the same ability to select languages via TheHeader in TheUserMenu in the top left of the app after logging in, while additionally being able to select your language directly from `SignupView`

**Comment by JonasThers** [comment]
Looking into this atm
