### ISSUE TITLE
[Feature]: Apply translation/localization to `GameOverDialog`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#631]
### Feature Summary

We should use `i18n` to translate the text in the `GameOverDialog`. See the following test for a quick way to look at this dialog:
```
it.only('Creates a match when two players play a ranked game for the first time this week', function () {
    // There should be two matches initially (one from last week and one with a different opponent)
    cy.request('http://localhost:1337/match').then((res) => {
      expect(res.body.length).to.eq(2);
    });

    // 1st game: Opponent concedes
    cy.concedeOpponent();
// COMMENT OUT THE REST OF THE TEST BELOW THIS LINE
```
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/a280fd65-87ff-4a46-9845-b5a7d4d38217)

### Detailed Description

We should pull all of the text in the GameOverDialog into the translation json files e.g. src/translations/en.json, src/translations/es.json, and src/translations/fr.json in under a key called `"game.dialogs.gameOverDialog"`

Look at src/views/LoginView for an example of a page that is correctly using $i18n to localize/translate content. The user-visible strings have been removed from the code and placed into a "login" section of the translation files in src/translations.

The page then imports and consumes the useI18n() composable to grab the t() function used to render/translate text by pulling from the appropriate language's json file. This is done using a setup() block of the page like so:

```
setup() {
const { t } = useI18n();
return { t };
},
```
From there, we can grab a given string by name in the appropriate locale using {{ t('login.joinDiscord') }} since each translation json in this case has a login attribute for all the text in the login page, with a joinDiscord child attribute for the text to show in the 'Join our discord community' button.

We should do the same thing to the GameOverDialog by extracting all the text in the page into a rules section of each translation json file (e.g. src/translations/en.json) and then configuring GameOverDialog.vue with the useI18n() composable and rendering all its text with t() to translate it to the user's selected locale.

All the text for the GameOverDialog should be stored in each language file under the key "game.dialogs.GameOverDialog" (generally we have one top-level key for each page e.g. "game" and "login", then specific sub-keys for components in that page (additionally grouping all the dialogs under the sub-key "game.dialogs"

The end result of this change should be the ability to see the text of the GameOverDialog in your preferred locale.

**Comment by Vivy24** [comment]
Hi @itsalaidbacklife , could I work on this issue?
