### ISSUE TITLE
[Feature]: Apply translations/localization to the `OpponentRequestedStalemateDialog`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#632]
### Feature Summary

We should use `i18n` to translate the `OpponentRequestedStalemateDialog`. See the following test for an example of where to see this component:
```
// tests/e2e/specs/in-game/gameOver.spec.js
it.only('Ends in a stalemate when opponent requests a stalemate and player agrees', () => {
```
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/2706b43d-b6e9-4a5c-b367-a6ef3126a250)

### Detailed Description

We should pull all of the text in the OpponentRequestedStalemateDialog into the translation json files e.g. src/translations/en.json, src/translations/es.json, and src/translations/fr.json in under a key called "game.dialogs.opponentRequestedStalemateDialog"

Look at src/views/LoginView for an example of a page that is correctly using $i18n to localize/translate content. The user-visible strings have been removed from the code and placed into a "login" section of the translation files in src/translations.

The page then imports and consumes the useI18n() composable to grab the t() function used to render/translate text by pulling from the appropriate language's json file. This is done using a setup() block of the page like so:

```
setup() {
const { t } = useI18n();
return { t };
},
```
From there, we can grab a given string by name in the appropriate locale using {{ t('login.joinDiscord') }} since each translation json in this case has a login attribute for all the text in the login page, with a joinDiscord child attribute for the text to show in the 'Join our discord community' button.

We should do the same thing to the OpponentRequestedStalemateDialog by extracting all the text in the page into a rules section of each translation json file (e.g. src/translations/en.json) and then configuring OpponentRequestedStalemateDialog.vue with the useI18n() composable and rendering all its text with t() to translate it to the user's selected locale.

All the text for the OpponentRequestedStalemateDialog should be stored in each language file under the key "game.dialogs.OpponentRequestedStalemateDialog" (generally we have one top-level key for each page e.g. "game" and "login", then specific sub-keys for components in that page (additionally grouping all the dialogs under the sub-key "game.dialogs"

The end result of this change should be the ability to see the text of the OpponentRequestedStalemateDialog in your preferred locale.

**Comment by LSvincak** [comment]
I can work on this

**Comment by itsalaidbacklife** [comment]
@LSvincak have at it! Please feel free to ask any questions about the issue here in this thread. Or if you'd like real time support, you can use the #code channel of the Cuttle [discord](https://discord.gg/zbzVs3PXxQ) to chat with myself and the other devs synchronously. Good hacking!
