### ISSUE TITLE
[Bug]: French How it Works Button Spills to the next line

### ISSUE THREAD

**Issue by AlexVCS** [cuttle-cards/cuttle#667]
### Bug Summary

French How it Works Button Spills to the next line

### Detailed Description

For the French version of the site this currently happens with the how it works and join Discord button:

<img width="636" alt="Screenshot 2023-10-10 at 7 51 58 PM" src="https://github.com/cuttle-cards/cuttle/assets/49458917/766e105f-efb9-4a74-b568-40a08421ec73">

Potential solutions suggested on Discord:
We could potentially scale down the button per language
We could scale it down for every language

### Current Behavior

When you translate the page into French you'll see the button is below the join discord button.

### Steps to Reproduce

1.
2.
3.

**Comment by itsalaidbacklife** [comment]
Resolved by #679 

@JonasThers a process nitpick, when linking issues to PR's, in addition to the issue number itself please include the word "Resolves" in front e.g. "Resolves #667" as that will automatically close the issue when the PR is merged. Nice work on this one; thanks for your contribution!
