### ISSUE TITLE
[Feature]: Add Stalemate info to rules FAQ

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#668]
### Feature Summary

We should update the rules FAQ to describe what happens if the deck is exhausted (and how stalemates work)

### Detailed Description

We should update the `RulesView.vue` file so that the FAQ section correctly describes what happens when there are no more cards. We should put the new question and answer after "What if I play a Seven and there is only one card left in the deck?" and before "Where can I play Cuttle?" (this should become the second-to-last question).

Specifically, we should add the question and answer as follows:

### What happens when the deck is exhausted?
When there are no cards left in the deck, players may pass on their turn instead of drawing. If there are three consecutive passes i.e. player 1 passes, player 2 passes, then player 1 passes again, the game ends in a stalemate and neither player wins.

**Comment by bobonlan** [comment]
Gonna try and knock this one out

**Comment by bobonlan** [comment]
Finished!
