### ISSUE TITLE
[Feature]: Enable joining a lobby by sharing a link to your current game

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#674]
### Feature Summary

It would be convenient to be able to invite someone directly to your game from the lobby view to avoid the need to tell them which specific game to join using its name. We should allow direct navigation to a game lobby to direct users to authenticate if necessary and then to join the game

### Detailed Description

The intended flow is that a user who is sitting in the lobby can copy their url bar and send it to another user who could then navigate directly to their game and take care of all the appropriate setup in the database. 

This has two main parts:

1. If a user navigates to a specific lobby without being logged in, we should redirect them to the `LoginView` and set a query param that the LoginView uses to redirect them _back to that game lobby_ after successful authentication
2. When the `LobbyView` is created, it should check in the `gameStore` to confirm that the user has the game data and has properly subscribed to the game. If the game data is _not_ present (i.e. the user directly navigated to this url without first going home and clicking the join button), then we should fire off the `gameStore.requestSubscribe()` action with the id from the lobby url. 

Notably for 2) we should use a loading state while the request to join the lobby is being processed (a v-skeleton loader would be appropriate) and if the request to join the game fails (e.g. another person already joined before you clicked the link), we should show a dialog that says 
"Oops

Could not join that game at this time. Go home to find another one!"

with a button to "Go Home" that directs the user to the HomeView.

This way users will be able to share links to their current lobby so other players can directly join their game, and we'll appropriately authenticate and join the game, and handle errors by going home.

**Comment by Rafajrg21** [comment]
I will be working on this issue, if someone has done some work on this or has any feedback, you can dm me on the Cuttle discord

**Comment by psinha0** [comment]
Hey @Rafajrg21 have you made any progress in this? I couldn't find your discord so I couldn't DM you, but I'd like to work on this alongside you if that's alright!
