### ISSUE TITLE
[Bug]: When spectating, the top player's hand is not sorted

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#702]
### Bug Summary

When viewing a game as a spectator, you see p0's hand at the bottom correctly sorted, but p1's hand above is not sorted

### Detailed Description

See example image from a spectated game:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/316b6eca-e15f-48c3-9d2c-6c5076d7c344)

This is a direct result of the updates in #698 which deliberately does not sort the opponent hand when you are _playing_ the game. We should update the `gameStore.updateGame` function so that the opponent's hand is sorted only if you are viewing as a spectator

### Current Behavior

- Only the bottom player (p0)'s hand is sorted when viewing as a spectator (incorrect)
- Only your own hand is sorted when viewing as a player (correct)

### Expected Behavior

- Both players' hands are sorted when viewing as a spectator (this is the change)
- Only your own hand is sorted when viewing as a player (this should stay the same)

### Steps to Reproduce

1. Join a game as a spectator
2. Look at the top player's hand
3. See it isn't sorted

**Comment by byarmis** [comment]
> the opponent's hand is sorted only if you are viewing as a spectator

I suppose the hand should be sorted also if you're viewing the opponent's hand because you have a Glasses 8 on the board as well

**Comment by Haviles04** [comment]
I'll work on this :D
