### ISSUE TITLE
[Bug]: LobbyView is not playing a sound when players join

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#707]
### Bug Summary

The LobbyView is supposed to play a sound when a player joins but this is not happening. 

### Detailed Description

When your opponent joins the lobby you're in, you are supposed to hear a sound effect of some water to indicate that a change has happened and you have an opponent. This was implemented in #364 and fixed up in #387, but it appears no longer to be functional. 

It looks to be the case that the two `<audio>` tags with refs for `enterLobbySound` and `leaveLobbySound` have been removed from the LobbyView. We should re-add them and test that this still works.

### Current Behavior

The LobbyView does not make sounds when players join and leave

### Expected Behavior

The lobby should make one sound effect when a player joins, and another when they leave

### Steps to Reproduce

1. Log in, create a game, and join it
2. Have another player join your game
3. A sound should play but doesn't
4. Have that player leave
5. A different sound should play but doesn't

**Comment by anudeeps352** [comment]
I might try checking this issue out
