### ISSUE TITLE
[Feature]: French translations could more accurate

### ISSUE THREAD

**Issue by Posoroko** [cuttle-cards/cuttle#709]
### Feature Summary

Use less literal translations

### Detailed Description

When looking around, I saw a few translations (French) that could be improved.  Most of them seem to just be the literal translation.  For example, "game" can be translated to "jeu" and to "partie".  jeu = game, partir=match.  Cuttle is a game, do you want to make a match?  Nobody in french would say would use "jeu" (game) instead of "partie"  (match).  Except in tennis where they say "jeu, set, match". But that really is an exception.
So, if you want, you can open an issue and I can go over the French translation file and make corrections so it's more accurate.

**Comment by itsalaidbacklife** [comment]
@Posoroko that makes complete sense and would be a significant improvement. So far the translations have been mostly put together by non native speakers, using google translate, which makes them very literal and full of guesswork. 

Having a fluent French speaker review and correct the French language file would be great!

**Comment by Posoroko** [comment]
To make sure I get the translations to reflect the "Cuttle feel" by using appropriate words and expressions, I will need to get some feed back from the players on Discord.  It would be easy to loose the whole "under the sea" thing by just translating too quickly.  I could then write down some notes about the vocabulary for future translators.

**Comment by itsalaidbacklife** [comment]
> I've been thinking about this myself, despite also using Google Translate. I don't know exactly what I'm trying to suggest, but should this maybe somehow be added to the guidelines? Maybe that we should be careful about using Google Translate, and maybe ask for help on Discord, in case there are native speakers or people with knowledge of the given languages?

The whole system is fairly new so we don't have a definitive process, but imo this is a totally reasonable approach: any developer can apply the translation system to a given area of the application and if we get feedback from native speakers that a translation should be adjusted, we update it accordingly. That's easier to do once translations are already applied that part of the UI so it's still meaningful progress to work in the way we've been doing it imo.

Some day we could add a feature to allow users in the app to directly submit translations corrections for review, which could streamline the process. But for now, feedback and iteration in just this way seems perfectly reasonable

**Comment by itsalaidbacklife** [comment]
Closed by #746 

FYI @Posoroko in order to make the PR automatically close the issue, it needs to specifically have a keyword in front of the issue number e.g. "Resolves #709" -- it's not enough to put #709 itself in the PR description without the word "Resolves" or "Fixes" in front of it.

So the PR template actually has a section for this down below where you've been putting it. The issue number should go below the header where you've been putting it like this:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/9a4d0ffd-4c5f-4f6c-a772-141c11591c93)
