### ISSUE TITLE
[Feature]: Animate when players enter the lobby

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#710]
### Feature Summary

When your opponent joins your lobby we should animate the appearance of their player indicator to juice up the interaction

### Detailed Description

The lobby has player indicators for each player (you and your opponent) with three possible states: no player, player who isn't ready, and player who is ready. When a player hits ready, their indicator nicely animates to transition from a card back to a card front displaying the word, "ready". See this video demonstrating:

https://github.com/cuttle-cards/cuttle/assets/6520704/6b7bc531-7f68-4ed3-9e4e-020a8078b643

It would be nice to add an additional animation for when a player _joins_ the lobby and we transition from no-player to player-who-isn't ready yet. This could juice up the interaction to be more consistent with the 'Ready' interaction

**Comment by Rafajrg21** [comment]
@itsalaidbacklife I think you closed this issue by accident?

**Comment by itsalaidbacklife** [comment]
Yep I linked the wrong issue. Thanks @Rafajrg21
