### ISSUE TITLE
[Bug]: Card not displaying the right value

### ISSUE THREAD

**Issue by Posoroko** [cuttle-cards/cuttle#720]
### Bug Summary

After getting ready, exiting and joining again, player is shown as "ready"

### Detailed Description

On Firefox and chrome, the card can show "ready" when the player is not ready.  The variable "playerReady" for the other player shows "true" instead of "false".  

I recreated this bug in local and in production.

### Current Behavior

When a player does "playerReady = true", exit the lobby and come back, the other player sees them as "ready".

### Expected Behavior

A player comming back to the lobby should (I think) always be "not ready"

### Steps to Reproduce

1. create a game
2. player 0 joins the lobby
3. player 1 joins the lobby
4. player 1 get "ready"
5. player 1 exits the lobby
6. player 1 joins the lobby again

(I added an element to display the state of "playerReady" under each card)

Player 0 sees player 1's card as "ready" and the "playerReady" variable for player 0 equals "true".  
![bug a - player 0 ](https://github.com/cuttle-cards/cuttle/assets/73071377/381e65ec-861d-450c-a411-5fc36f9cf9e2)

Player 1 sees cards correctly
![bug a - player 1](https://github.com/cuttle-cards/cuttle/assets/73071377/f57067ff-bd94-44cc-bc5c-497f2cf4f1a7)

7. Player 0 gets "ready"

Player 0 can see both card are "ready", when that shouldn't be possible.
![showing ready when is not](https://github.com/cuttle-cards/cuttle/assets/73071377/47a7b280-789a-440b-b736-d6ee1e2d977b)

At the same time, player 1 sees the expected behavior.
![seeing cards correctly](https://github.com/cuttle-cards/cuttle/assets/73071377/203b92d6-c92a-4cd6-b84f-93b756863874)

**Comment by itsalaidbacklife** [comment]
@Posoroko are you able to reproduce this with a test case?

**Comment by Posoroko** [comment]
@itsalaidbacklife by writing a test? I can try. In the lobby.specs.js file?

**Comment by itsalaidbacklife** [comment]
@Posoroko exactly

**Comment by Posoroko** [comment]
I adapted the tests to test this bug.  Clearly, the p1Ready or p0Ready of the opponent doesn't get updated when they leave the game.  I added some code in the opponentLeft() method in stores/game.js that triggers the updateReady() method and it works fine now.  I don't know if this was missing or if it's a bug somewhere else that keeps it from happening.  Code review, someone?
