### ISSUE TITLE
[Bug]: Can't close the snackbar in the `LobbyView` using its 'X' button

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#739]
### Bug Summary

The `LobbyView` has a snackbar that appears when you the game is changed from ranked to casual or vice versa. It should be possible to click the 'X' button in this snackbar to close it, but this button doesn't work.

### Detailed Description

See pic:
![image](https://github.com/cuttle-cards/cuttle/assets/6520704/bd996c19-3c28-4108-88e1-0aa32382f44a)

This instance of `BaseSnackbar` in the `LobbyView` closes on a timeout (as it should), but it does not respond to clicking the 'X' button. We should investigate this page to identify why the snackbar doesn't close when you click the X button.

### Current Behavior

Clicking the 'X' button does not close the snackbar.

### Expected Behavior

Clicking the 'X' button does close the snackbar.

### Steps to Reproduce

1. Signup/log in
2. Create a game
3. Join the game
4. Hit the switch to change from ranked to casual or casual to ranked
5. See the snackbar in the bottom of the screen and click its 'X' button
6. Notice that the snackbar does not close

**Comment by mal092** [comment]
Hello, I would like to work on this issue.
