### ISSUE TITLE
[Feature]: Set in-game dialog widths to max-width=600px

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#74]
### Feature Summary

The in-game dialogs are awkwardly wide. We should fix their width to a maxiumum of 600px.

### Detailed Description

See all the dialog components that are instantiated inside the `GameDialogs.vue` component. Each of those children instantiates a `v-dialog`. Some of those `v-dialogs` have a max-width set and some don't. We should set all of them to have the same max-width for consistency's sake. Try '750' to see how it looks, and then consider smaller, using your best judgement. Try them on mobile as well as desktop for reference

**Comment by jerryh-jr** [comment]
@itsalaidbacklife and @seriouslysean what do you think about me grabbing this?
