### ISSUE TITLE
[Bug]: Player counts on games in the home view can be negative or greater than two

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#745]
### Bug Summary

The HomeView shows games available to join. They should show 0/2, 1/2, or 2/2 players. Sometimes they can show -1/2 or 3/2

### Detailed Description

See pic:
![Screen_Shot_2023-11-02_at_12 27 26_PM](https://github.com/cuttle-cards/cuttle/assets/6520704/88d8f2f2-0848-44c5-9523-5e45ab8260dd)

This happens sometimes when socket messages are missed intermittently e.g. to players join a lobby and then leave it, but the your client misses the second player joined. So the event stream looks to your client like: join, leave, leave. This sets the player count to -1 instead of zero.

To fix this easily we can update the gameList store so that the `joinGame()` and `otherLeftGame()` actions which increment and decrement player counts use `Math.min()` and `Math.max()` respectively to ensure that the player count never goes above 2 or below 0. So instead of 
```
updatedGame.numPlayers++;
```

we’d have
```
updatedGame.numPlayers = Math.min(2, updatedGame.numPlayers + 1)
```

and the reciprocal for otherLeftGame 

### Current Behavior

The player counts of games in the gameList can sometimes be < 0 or > 2.

### Expected Behavior

The player counts are always either 0, 1, or 2

### Steps to Reproduce

1.
2.
3.

**Comment by mal092** [comment]
Hello, I would like to work on this issue. Please assign me.

**Comment by Pooja1672** [comment]
Hi @itsalaidbacklife , I would love to work on this issue can you please assign it to me?
