### ISSUE TITLE
[Bug]: Lobby game type change notifications are not dismissable

### ISSUE THREAD

**Issue by meichthys** [cuttle-cards/cuttle#781]
### Bug Summary

Lobby game type change notifications are not dismissable

### Detailed Description

![image](https://github.com/cuttle-cards/cuttle/assets/10717998/f1f2a945-8638-43df-aab0-4f10425f1a33)
The X here doesn't do anything.

**Comment by itsalaidbacklife** [comment]
This looks like #739 which should now be fixed. Can you try hard refreshing the page and confirming if this is still and issue?
