### ISSUE TITLE
[Feature]: Translate the rematch text in the `GameOverDialog`

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#789]
### Feature Summary

The GameOverDialog has buttons and text about whether to replay your opponent in a new "rematch" game. This text should be translated using i18n the same as the rest of the `GameOverDialog` content

### Detailed Description

Specifically, the `GameOverDialog` has these paragraphs of text:
```      
       <p v-if="opponentWantsToRematch" data-cy="opponent-wants-rematch">
        {{ gameStore.opponent.username }} wants to rematch
      </p>
      <p v-if="opponentDeclinedRematch" data-cy="opponent-declined-rematch">
        {{ gameStore.opponent.username }} declined rematch and left the game
      </p>
```

These should be translated in the existing `game.dialogs.gameOverDialog` section of the existing language files. The necessary text "wants to rematch" and "declined rematch and left the game" should be added to all available language json files in `src/translations` e.g. `en.json`, `es.json` and `fr.json`

**Comment by Haviles04** [comment]
> Hi can I do this one ?

Sure! Help yourself, we are here to help in the discord if you need any :D

**Comment by kawaljen** [comment]
Hey, i realise that the translation is not implemented in the rematchView.vue, should i do it too ?


         <h1 :class="[$vuetify.display.xs === true ? 'text-h5' : 'text-h3', 'overlay-header']">
            Waiting for Game to Start
          </h1>

**Comment by Haviles04** [comment]
> Hey, i realise that the translation is not implemented in the rematchView.vue, should i do it too ?
> 
> 
>          <h1 :class="[$vuetify.display.xs === true ? 'text-h5' : 'text-h3', 'overlay-header']">
>             Waiting for Game to Start
>           </h1>

I believe issue #806 addresses this
