### ISSUE TITLE
Frozen Cards: Update MoveChoiceOverlay to prevent playing frozen cards, with Error message

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#79]
### Feature Summary

The MoveChoiceOverlay should be updated to make it more clear that you cannot play a card that is frozen.

### Detailed Description

The MoveChoiceOverlay has validation logic to disable move choices with an error message when a move is not allowed e.g. when it is not your turn or when a move has no legal target.

See the image below for an example: the middle move is disabled because there is nothing you can scuttle with the selected card:
![D00D52E0-72D7-435C-BBCF-FC56C1402193](https://user-images.githubusercontent.com/6520704/189488312-330dbf4b-b7fa-46c8-ba45-0d03d7de4107.png)

Currently, there is no such indication that a move is illegal because the selected card is frozen. We should:

1. Disable every move choice when a frozen card is selected with the error message “This card is frozen” (MoveChoiceOverlay.vue)
2. Set the selected card’s `frozen` prop to true if the selected card is frozen (MoveChoiceOverlay.vue)
3. Update the tests so that the ones from the player’s perspective about playing frozen cards correctly expect the MoveChoiceOverlay to prevent them from submitting the move (currently you can submit the move and then get an error snackbar), and ensure there is an additional test that plays the frozen card from the opponents perspective (this should directly trigger the request without the UI, sidestepping the disabled state of the MoveChoiceOverlay) and assert that the same error snackbar we currently see still appears in that case.

**Comment by TommySchmid** [comment]
@itsalaidbacklife comment from Discord:

`We could break it up into pieces. The first I think being to apply the frozen prop to the selected card in the MoveChoiceOverlay. Basically when you’re looking at a the moves you can make with a card, if that card is frozen (was just returned to your hand by your opponent using a 9 and preventing you from playing it this turn) then in addition to showing that in your hand, we can show it in the overlay that displays your move choice options`

**Comment by itsalaidbacklife** [comment]
Closed by #83 + #99
