### ISSUE TITLE
[Feature]: Show the second card flip to ready in the lobby

### ISSUE THREAD

**Issue by Rafajrg21** [cuttle-cards/cuttle#791]
### Feature Summary

When the first player ready up and then the second player hits the ready button, we should see the card flip to show the ready state as well

### Detailed Description

Right now, when our opponent is already in the ready state and we hit the ready button, we jump immediately to the game and we don't see our card turn ready like it should. 

To resolve this we need to trigger the game start event **after** we finish the second player "ready" animation.

**Comment by itsalaidbacklife** [comment]
Closed by #729
