### ISSUE TITLE
[Feature]: Implement redesigned 'Rules'/'About' page

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#814]
### Feature Summary

As a part of the app-wide initiative to redesign the out-of-game experience, we have designed a new iteration of the rules page which better captures the look and feel of the rest of the site.

### Detailed Description

Here is the [design file](https://www.figma.com/file/7Z0jKHSkoS7dixGO3TDxQl/Cuttle_About_Page?type=design&node-id=3-4058&mode=design&t=wisFXGzcFAWZu1Np-0).

The major changes are:
1. Introduction of jump-link navigation to quickly navigate to specific sections
2. Adjusting the color scheme to be consistent with the rest of the app
3. Removing the static image previews for each move and revealing the gif for a single move at a time in a dialog (rather than showing it in place).

**Comment by kawaljen** [comment]
Hi can I work on this one ?

**Comment by itsalaidbacklife** [comment]
Hi @kawaljen, @haaarsh619 has already started on this issue so it may be best to let them wrap that PR to avoid double work, though there may be a checkpoint where it's reasonable to merge what's there and then add further details/changes to completely match the design in a separate update, which you could help with.

In the mean time, would you like to take a stab at this frontend issue? https://github.com/cuttle-cards/cuttle/issues/446

If you'd like to discuss on discord, I'd be happy to help you find an issue that suits your interests.
