### ISSUE TITLE
[Bug]: Three animation goes wrong direction for player who used the three

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#827]
### Bug Summary

When a player chooses a card from the scrap with a three, it is revealed to both players in the scrap and animated towards the player's hand. The animation goes the wrong direction for the player who played the three.

### Detailed Description

See the video below. When the player picks the ten of hearts from the scrap, it is animated upwards towards their opponent, except we are seeing the perspective of the user who played the three, so the 10 of hearts should move _down_ towards their hand.

https://github.com/cuttle-cards/cuttle/assets/6520704/2bbe3dbd-3292-4972-a9cc-329e5cd86a5d

As a dev note, this animation was working correctly before, so the fix will likely be in troubleshooting the `case SocketEvent.RESOLVE_THREE:` of the `inGameEvents.js` file and its corresponding call to `gameStore.processThrees()`.

### Current Behavior

Cards picked from the scrap pile are always animated upwards towards your opponent, even for the player who played the three.

### Expected Behavior

The person who played the three should see the card animate down towards their hand, and their opponent should see the card animate upwards (so it always goes toward the hand of the player who gets the card).

### Steps to Reproduce

1. Sign in/up, join and start a game
2. Have either player put card(s) into the scrap
3. Have one player play and resolve a three, then pick a card from the scrap
4. Look at the screen of the person who played the three, watch how the card chosen from the scrap animates upwards (not downwards).

**Comment by Haviles04** [comment]
This should be fixed by #832
