### ISSUE TITLE
[Bug]: Rule Formatting seems to have regressed

### ISSUE THREAD

**Issue by meichthys** [cuttle-cards/cuttle#897]
### Bug Summary

Rule formatting isn't great

### Detailed Description

I think the formatting in the rules dialog used to be better. It is currently:
![image](https://github.com/cuttle-cards/cuttle/assets/10717998/c00f02c3-8a74-4838-bd82-1bdacac10be7)

**Comment by kawaljen** [comment]
Hey can i work on this one? 
If yes, should i make it looking like the /rules page, but with smaller titles and images ?
Should the text be updated to match the /rules page ?

**Comment by itsalaidbacklife** [comment]
> Hey can i work on this one? 
> 
> If yes, should i make it looking like the /rules page, but with smaller titles and images ?
> 
> Should the text be updated to match the /rules page ?
> 
> 

Yes, that would be great. Let's match the style and content as much as possible, reusing components where it's practical to do so

**Comment by kawaljen** [comment]
ok, so what do you think about replacing the text by the rulesviews component ?
and add a floating X close button to easily close the modal?

**Comment by itsalaidbacklife** [comment]
> ok, so what do you think about replacing the text by the rulesviews component ?
> 
> and add a floating X close button to easily close the modal?
I think the only issue with that may be the navigation, which seems like it may not work nicely in a modal. 

We can try it and see how it goes.  If the left-nav doesn't work inside the modal, we could add a prop to the RulesView either to force it to use the top-nav, or you remove the nav altogether, and set that inside the dialog (but not from the page route).

Alternatively if the whole setup looks wonky, we could pull the shared content into a sub-component of the RulesView and use that in both the RulesView and RulesDialog

**Comment by kawaljen** [comment]
ok,
A prop will be needed to hide some content on the rule modal, like the 'ready to play, find a game' button..

About the nav, to me,  it is not bad on a desktop vue, also I find it usefull, 
but I find it is a bit busy on mobile vue, as with the modal, only two links are visible

![Screenshot 2024-05-21 123900](https://github.com/cuttle-cards/cuttle/assets/7325003/e3d506ed-7c16-435a-b7cc-fbb31da2a077)
![Screenshot 2024-05-21 123844](https://github.com/cuttle-cards/cuttle/assets/7325003/52cd8c40-badc-473b-be23-fb47bb15d296)
