### ISSUE TITLE
[Bug]: Playing multiple 5's allows you to skip discarding

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#901]
### Bug Summary

Playing a 5 doesn't correctly clear out the card seleted for discard such that playing a second 5 allows you to cheat by not discarding.

### Detailed Description

Playing a 5 requires the player to discard a card, then draw 3, but the dialog is bugged to allow you to "discard" the card you discarded last time even if it's not in your hand.

### Steps to Reproduce

1. Play a 5
2. Play a second 5 and hit "Discard and draw" without selecting a new card for discard
3. You'll draw 3 cards without discarding

**Comment by Haviles04** [comment]
fixed by #902
