### ISSUE TITLE
[Feature]: Translate the values still in English in the Spanish and French translation files

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#907]
### Feature Summary

Some of the Spanish and French translation files (`es.json` and `f.json`) still have English text for several strings. We should translate all such strings into their respective languages.

### Detailed Description

To do this, look in `src/translations/es.json` and `src/translations/fr.json` for any strings still written in English and translate them into Spanish or French (to match the respective file).

**Comment by kawaljen** [comment]
Hey 
In french i haven't seen much to fix, so I 'll let a spanish speaking person handle it, 

 I've notice one piece of text in english though, which is :
noJackWithQueen": "You cannot use a Jack while your opponent has a Queen". -> Vous ne pouvez pas jouer un Valet car votre adversaire a une Reine.

And a small mistake here :
"strongest": "le plus for" --> "le plus for**t**" (whith a T at the end)
