### ISSUE TITLE
[Feature]: RulesView (Mobile Portrait)- programmatically scroll the top nav when highlighting its jump link 

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#915]
### Feature Summary

Scrolling to a section of the RulesView automatically highlights its corresponding jump link in the nav. On mobile devices, it should also horizontally scroll that jump link into view

### Detailed Description

On portrait mobile, the RulesView uses a top nav with horizontally scrolling jump links to the various sections. The currently in view section is programmatically highlighted:
![IMG_5453](https://github.com/cuttle-cards/cuttle/assets/6520704/0628aaa0-b6e0-4a6d-8066-2f0f4e87e1e5)

However scrolling to a section does not horizontally scroll the top nav so that the newly highlighted jump link is guaranteed to be visible. This results in seeing no highlighted jump links: 
![IMG_5454](https://github.com/cuttle-cards/cuttle/assets/6520704/52710473-7d6d-47fb-892e-360ea8599716)

To fix this, we should update the onIntersect() handler to use Vuetify’s goTo() function (already used to make the jump links “jump”) to go scroll the specified jump link into view at the same time that it highlights the link.

**Comment by kawaljen** [comment]
Hey is that still ok to work on that one?

**Comment by itsalaidbacklife** [comment]
> Hey is that still ok to work on that one?

Yep; have at it!
