### ISSUE TITLE
[Feature]: Create `unpackGameState` helper to convert `GameStateRow` row to full `GameState` object

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#940]
### Feature Summary

We need to define the `unpackGameState()` utility to transform the `GameStateRow` database rows into `GameState` objects.

### Detailed Description

See the [spec](https://docs.google.com/document/d/1vYe4xoVULIbbFU2yhErok-Qm1cg8ujMGNqlUOgNXLwE/edit). Game states are stored in the database as `GameStateRow` objects, which use specially formatted strings to represent the cards, but the actual game logic is performed on `GameState` objects, which are to be created via the new `unpackGameState` helper.

This helper should input a `GameStateRow` as defined in the spec and output a `GameState` as defined in the spec. Specifically, this will involve converting all the `String` representations of cards to the `Card` objects, and aggregating the p0Hand, p0Points, and p0FaceCards attributes into the `p0: Player` object (doing the same for p1).

This update should include backend unit tests that confirm that `unpackGameState` correctly processes specified `GameStateRow` objects into the expected `GameState` result.

**Comment by kawaljen** [comment]
Hey
I am working on this one if that is ok. 
Can you explain what the content between parentheses refers to in the card model (attachement, twos etc)  in TH(JH-p0,JC-p1,JD-p0)

**Comment by itsalaidbacklife** [comment]
> Hey
> 
> I am working on this one if that is ok. 
> 
> Can you explain what the content between parentheses refers to in the card model (attachement, twos etc)  in TH(JH-p0,JC-p1,JD-p0)

The parentheses represent cards that are attached to the preceding card, and which player controls them

So `"TH(JH-p0,JC-p1,JD-p0)"` represents the Ten of Hearts, with three jacks on it: hearts (on bottom and controlled by p0), clubs (controlled by p1), and diamonds, controlled by p0 (on top). 

See the games state string section of the spec: https://docs.google.com/document/d/1vYe4xoVULIbbFU2yhErok-Qm1cg8ujMGNqlUOgNXLwE/edit

**Comment by kawaljen** [comment]
Hey I think I am quite done with this one, probably some more testing to do though.  I am creating a pull request, to let you review.

**Comment by kawaljen** [comment]
Hey
I think I am quite done with this one. I end up doing the converting of  GameStateRow row to full GameState object , and this opposite,  converting of  GameState to full GameStateRow..
