### ISSUE TITLE
[Feature]: Implement playing Jacks in the GameState API

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#949]
### Feature Summary

We need to implement playing Jacks in the GameState API in order to support the full game logic in this API. See the [spec](https://docs.google.com/document/d/1vYe4xoVULIbbFU2yhErok-Qm1cg8ujMGNqlUOgNXLwE/edit#heading=h.wpeuh0qc6ps2) for a general overview of the API, its underlying motivations, and the development approach.

Playing a jack should result in the `playedCard` moving from the requesting player's `hand` to the `attachments` on the `targetCard`, and the `targetCard` moving from the opponent's `points` to the requesting player's `points`. It should also increment the turn and set the `phase` to `GamePhase.MAIN`.

### Detailed Description

Implementation should take the general approach shown in the [Backend Control Flow section of the GameState API Spec](https://docs.google.com/document/d/1vYe4xoVULIbbFU2yhErok-Qm1cg8ujMGNqlUOgNXLwE/edit#heading=h.vgf103gono5r) and follow the example of #1025 

Making this move, like all others, will be triggered via the endpoint:

```
POST /api/game/:gameId/move
```
Which move gets made is determined by the request body, which should specify a moveType field with a value from the MoveType enum. Playing a jack will be triggered by sending a request body like:

```
{ moveType: MoveType.JACK, playedCard: 'JH', targetCard: '7D'};
```
When a `moveType: MoveType.JACK` is sent in the req body, the endpoint will attempt to utilize the `jack` helpers: `sails.helpers.gamestate.moves.jack.validate()` and `sails.helpers.gamestate.moves.jack.execute()`. Each of these should follow the paradigm outlined in the [docs](https://docs.google.com/document/d/1vYe4xoVULIbbFU2yhErok-Qm1cg8ujMGNqlUOgNXLwE/edit#heading=h.vgf103gono5r):

There are four pieces to implement:
1. update the `api/policies/hasValidMoveBody` policy to allow and validate requests with a moveType of `MoveType.JACK`
2. Implement the `api/helpers/gamestate/moves/jack/validate` helper to verify if the move is legal
3. Implement the `api/helpers/gamestate/moves/jack/execute` helper to create a new GameState that plays a jack for the requested player to steal their opponent's point card
4. Unskip the relevant tests by removing the `cy.skipOnOnGameStateApi()` commands from tests which can now pass in the GameState API

### Updating the `api/policies/hasValidMoveBody` policy
We must also update the policy `api/policies/hasValidMoveBody.js` to accommodate the `MoveType.JACK` moveType. This policy is already applied to the endpoint for making a move and it uses a `switch()` statement on `req.body.moveType` to validate that a given req body has all the data necessary for the given `moveType`. We should add a `MoveType.JACK` case to this policy.

A `moveType`  of `MoveType.JACK` requires a `playedCardId` and a `targetCardId` which are both valid card ids. If both `playedCardId` and `targetCardId` present in req.body and it can be found in `utils/DeckIds.json`, then we can `return res.next()` in this switch case. Otherwise we should return `res.badRequest()` with an error that explains which `req.body` attribute is missing or invalid.

### Implementing `validate()`
Create a new `api/helpers/gamestate/moves/jack/validate.js` helper file that matches the general setup of the existing `api/helpers/gamestate/moves/points/validate.js` helper. It should throw errors if the requested move is illegal. It should have three inputs: 
1. `currentState` - the unpacked `GameState` from before the move is made
2. `requestedMove` -req body describing the move being made3.
3. `playedBy` - 0 or 1 for whether p0 or p1 is making the move.

`validate()` should throw if:
* It is not the requesting player's turn
* The GameState's `phase !== GamePhase.MAIN`
* The `playedCard` is not in the player's hand (`throw new Error("game.snackbar.global.playFromHand")`)
* The `playedCard` is frozen (`throw new Error('game.snackbar.global.cardFrozen')`)
* The `playedCard` is not a jack (`throw new Error('game.snackbar.jack.stealOnlyPointCards')`)
* The `targetCard` is not in the opponent's `points` (`throw new Error('game.snackbar.jack.stealOnlyPointCards')`)
* The opponent has a queen in their `faceCards` (`throw new Error('game.snackbar.jack.noJackWithQueen')`)

### Implementing `execute()`
Create a new `api/helpers/gamestate/moves/jack/execute.js` helper file that matches the general approach of the existing execute helper `api/helpers/gamestate/moves/points/execute.js`. It should create and return a new `GameState` that is the result of making the `jack` move for the requested player i.e. **it should remove `playedCard` from the player's hand, and add it the `attachments` of the `targetCard`. It should then move the `targetCard` from the opponent's `points` to the requesting player's `points`. It should also increment the turn and set the phase to `GamePhase.MAIN`. The `playedBy`, `playedCard`, and `targetCard` attributes should be included in the returned `GameState`.

`execute()`  should have 3 inputs:
1. `currentState` - the unpacked `GameState` from before the move is made
2. `requestedMove` -req body describing the move being made
3. `playedBy` - 0 or 1 for whether p0 or p1 is making the move.

### Unskipping Tests
Because we are approaching the `GameState API project with a feature-flag approach, all changes are merged into the `main` branch and the application and tests are set to dynamically run in either the GameState API mode, or the legacy mode, based on the `VITE_USE_GAMESTATE_API` env variable. In CI, we run the full suite of tests against the legacy version of the application and then run a subset of the tests against the GameState API version of the application.

Which tests are run in the GameState API version of CI is controlled via the test command `cy.skipOnGameStateApi()` which programmatically skips a test if the env var `VITE_USE_GAMESTATE_API` is enabled. As we develop new features in the GameState API, we should remove the `cy.skipOnGameStateApi()` command from more and more of the tests.

**Essential tests**
For this PR, at minimum, we should unskip the following tests, which should be able to pass once it is working correctly. All the following tests are in the `tests/e2e/specs/in-game` folder:
* `basicMoves.spec.js` - `it('Player and Opponent plays Jacks on different cards')`
* `basicMoves.spec.js` - `it('Quadruple jacks successfully')`

You can run the tests against the GameState API locally by:
 booting the server in gamestate mode with
`npm run start:server:gamestate`

Then booting the client in gamestate mode with
`npm run start:client:gamestate`

running the tests in gamestate mode with
`npm run e2e:client:gamestate`.

**Comment by kawaljen** [comment]
Hello Can I work on this ?

**Comment by itsalaidbacklife** [comment]
> Hello Can I work on this ?

Have at it! Feel free to ask any questions as they arise
