### ISSUE TITLE
[Bug]: ReauthenticateDialog needs to wrap the input fields in a <form> to be valid HTML

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#97]
### Bug Summary

We should update the ReauthenticateDialog so that its inputs are wrapped in a <form> element

### Detailed Description

Currently the `src/client/js/components/GameVeiw/ReauthenticateDialog.vue` just holds the `<v-text-field>`s for submitting your login credentials in a simple `v-card` but the HTML spec requires that they be additionally wrapped in a `<form>` element. Following the example of the `LoginSignup` page, we can handle submission of the form using `@submit.prevent="login"` so that other form-submission logic doesn't fire

**Comment by cychu42** [comment]
Hello, I would like to handle this issue.

**Comment by itsalaidbacklife** [comment]
Awesome thank you! You can check out the main login page (`client/js/views/LoginSignup.vue`) for comparison
