### ISSUE TITLE
[DevEx]: Refactor cypress commands file to use a a centralized helper function for making socket requests

### ISSUE THREAD

**Issue by itsalaidbacklife** [cuttle-cards/cuttle#974]
### Improvement Summary

We should consolidate the cypress commands so that the socket api calls are made with a utility function like the `game` store's `makeSocketRequest()` function. This should DRY up the commands file and afford the flexibility to more centrally manage dynamically utilizing the GameState API vs the legacy API during development.

### Detailed Description

We should employ the same maneuver used in #971 to DRY up all the `io.socket.get()` calls from the various cypress commands. We can then additionally use the technique laid out in #973 where the `nonGameStateAPIMoves` are defined in a `Set` that is used to programatically alter the gamestate request urls when the `VITE_USE_GAMESTATE_API` env var is set. 

This will allow us to more concisely control which endpoints hit which urls in both the GameState and legacy APIs, while shortening up the commands file.

**Comment by Haviles04** [comment]
I'm gonna grab this one
